/* Actual source JSX/CSS through explicit hooks. Static fictional preview, NOT running React or the API. */
const fs=require('node:fs'),path=require('node:path');const {harness,toHtml,root}=require('../v10/source_harness.cjs');const dir=path.join(root,'preview/v15');fs.mkdirSync(dir,{recursive:true})
const css=['styles/tokens.css','styles/global.css','features/catalog/catalog.css','features/collection/collection.css','features/discovery/discovery.css','features/floorplan/floorplan.css','features/visit/visit.css','features/support/support.css','styles/polish.css','features/library/library.css'].map(p=>fs.readFileSync(path.join(root,'frontend/src',p),'utf8')).join('\n')
const pic=name=>'data:image/png;base64,'+fs.readFileSync(path.join(root,'frontend/public/assets/boothup',name)).toString('base64');const logo='data:image/png;base64,'+fs.readFileSync(path.join(root,'frontend/public/assets/brand/logo.png')).toString('base64');
const mk=(id,type,title,note,photo)=>{const memory={title,eventName:'[예시] 작은 창작 마켓',participantName:'[예시] 달토끼 공방',summary:'식물과 작은 동물을 모티브로 일상에 놓기 좋은 소품을 소개합니다.',tags:['식물','키링','선물']};return {id:`00000000-0000-4000-8000-${String(id).padStart(12,'0')}`,target:{type,eventId:10,id:type==='EVENT'?10:id,participantId:type==='EVENT'?null:20},revision:0,savedAt:'2026-09-16T02:00:00Z',updatedAt:'2026-09-16T02:00:00Z',day:'2026-09-15',hall:'1관',note,visitedDays:id===21?['2026-09-16']:[],available:true,saved:memory,current:{memory,operationState:'SCHEDULED',notice:'',venue:'서울의 가상 전시장',occurrences:[{startDate:'2026-09-15',endDate:'2026-09-16'}],locations:[{code:'B1',status:'ASSIGNED',hall:'1관',zone:null,startDate:'2026-09-15',endDate:'2026-09-16',floorPlanUrl:null}],evidenceScope:'EVENT_LISTED',price:{amount:'6000',currency:'KRW'},saleState:'PLANNED',links:[{label:'공식 상품·판매 안내',url:'https://example.com/fictional-product'}],publishedAt:'2026-09-16T00:00:00Z'},image:photo?{id,url:'https://preview.boothhana.test/assets/'+photo,credit:'저장소 디자인 예시 이미지',sourceUrl:'https://example.com/design-fixture'}:null,changed:false,lastOpenedAt:null}}
const rows=[mk(30,'PRODUCT','[예시] 달토끼 아크릴 키링','친구 선물 후보. 초록색 실물 확인하기.','moon-rabbit-keychains.png'),mk(20,'PARTICIPANT','[예시] 작은숲 공방','도자기 소품이 마음에 들었음. 집 선반 너비 확인.',null),mk(21,'PRODUCT','[예시] 고양이 스티커','다이어리 표지에 붙이기.','pixel-cat-stickers.png')]
rows.push({...mk(40,'PRODUCT','','나중에 상담했던 내용 다시 확인하기.',null),available:false,saved:null,current:null})
function expand(h,n){if(n==null||typeof n!=='object')return n;if(Array.isArray(n))return n.map(v=>expand(h,v));if(typeof n.type==='function')return expand(h,h.render(n.type,n.props,true));let children=expand(h,n.props.children);if(n.type==='select'&&n.props.value!==undefined)children=[children].flat(Infinity).map(c=>c?.type==='option'?{...c,props:{...c.props,selected:String(c.props.value)===String(n.props.value)}}:c);return {...n,props:{...n.props,children}}}
function page(mode){const guest=mode==='guest',items=mode==='empty'?[]:rows,lib={owner:guest?'guest':'member:1',index:items,guest:[],version:0,loading:false,error:'',refresh:async()=>{}}
 const h=harness({library:lib,location:{pathname:'/library',search:'',state:null},auth:{user:guest?null:{id:1,displayName:'방문자',permissions:['FAN','CREATOR']},loading:false,loginUrl:'/api/auth/login',logout:async()=>{}},remote:{loading:false,error:null,reload:async()=>{},data:{items,page:0,size:24,total:items.length,groups:[{eventId:10,name:'[예시] 작은 창작 마켓',count:items.length}]}}})
 const mod=h.load('frontend/src/features/library/LibraryPage.tsx');const content=expand(h,h.render(mod.LibraryPage,{},true));h.env.outlet=()=>content;const body=toHtml(expand(h,h.render(h.load('frontend/src/components/layout/PublicLayout.tsx').PublicLayout,{},true))).replaceAll('/assets/brand/logo.png',logo).replaceAll('https://preview.boothhana.test/assets/moon-rabbit-keychains.png',pic('moon-rabbit-keychains.png')).replaceAll('https://preview.boothhana.test/assets/pixel-cat-stickers.png',pic('pixel-cat-stickers.png'))
 const dialogs=items.map(entry=>toHtml(expand(h,h.render(mod.MemoryEditor,{entry,guest,trigger:null,close:()=>{}},true))))
 const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>부스하나 v15 · 내 보관함</title><style>${css}\n.preview-note{background:#263f50;color:white;padding:9px 18px;font:12px/1.7 system-ui}.preview-note a{color:white;margin-left:14px;text-decoration:underline}#demo-result{position:fixed;bottom:20px;left:16px;right:16px;background:#263f50;color:white;padding:14px;border-radius:10px;z-index:10000;display:none}</style></head><body><div class="preview-note">가상 데이터·정적 시안 · 실제 저장/로그인은 실행되지 않습니다. 메모·방문 기록 버튼은 보기용입니다.<a href="index.html">계정 보관함</a><a href="guest.html">기기 저장</a><a href="empty.html">빈 보관함</a></div>${body}<div id="demo-result" role="status"></div><script>
const dialogs=${JSON.stringify(dialogs).replaceAll('<','\\u003c')};
document.querySelectorAll('.memory-card').forEach((card,i)=>{const b=card.querySelector('button');if(b)b.addEventListener('click',()=>{const wrap=document.createElement('div');wrap.innerHTML=dialogs[i];const d=wrap.firstElementChild;document.body.append(d);d.showModal();d.querySelector('h2').focus();d.querySelector('header button').onclick=()=>d.close();d.addEventListener('close',()=>{d.remove();b.focus()});d.querySelector('form').onsubmit=e=>{e.preventDefault();alert('화면 확인용 시안입니다. 실제 앱에서는 개인 계정에 저장됩니다.');};d.querySelectorAll('button').forEach(x=>{if(x.textContent.includes('공유·QR')||x.textContent.includes('방문했어요')||x.textContent.includes('삭제'))x.onclick=()=>alert('실제 앱에서 사용할 수 있는 기능입니다. 이 시안은 서버와 연결되어 있지 않습니다.');})})});
document.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&a.getAttribute('href')?.startsWith('/')){e.preventDefault();const box=document.getElementById('demo-result');box.textContent='정적 시안입니다. 실제 앱의 저장·검색·이동은 설치 후 확인해 주세요.';box.style.display='block';setTimeout(()=>box.style.display='none',3500)}})
</script></body></html>`;fs.writeFileSync(path.join(dir,mode==='account'?'index.html':mode+'.html'),html)
}
for(const m of ['account','guest','empty'])page(m);console.log('3 source JSX/CSS static fictional collection previews; dialog script is not React/real API.')
