import {describe,it,expect} from 'vitest'
import {copySharedPlan,createShareInput,publicSnapshot,readManagedShares,safeShareUrl,shareSignature,shareStorageKey} from './sharing'
import {validatePlan,type Plan} from './model'
const plan:Plan={version:1,id:'a',title:'함께 가는 은혼 카페',purpose:'EVENT',day:'2026-10-09',start:'12:00',end:'18:00',area:'HONGDAE',style:'FAN',interests:{topics:['ANIME_MANGA'],subjects:['은혼']},updatedAt:'2026-10-05T01:00:00Z',stops:[{id:'b',kind:'EVENT',name:'긴토키 카페',address:'서울 마포구',point:{lat:37.55,lng:126.92},eventId:239,start:'13:00',duration:60,locked:true,note:'내 예약번호 12345',url:'/discover/239?day=2026-10-09',source:'CATALOG'}]}
describe('itinerary snapshot sharing privacy',()=>{
 it('whitelists nested coordinates and occurrence fields before upload',()=>{const nested={...plan,stops:[{...plan.stops[0],point:{lat:37.55,lng:126.92,privateEmail:'private@example.test'},occurrences:[{startDate:'2026-10-09',endDate:'2026-10-09',startTime:null,endTime:null,privateToken:'hidden'}]}]} as unknown as Plan;const snapshot=publicSnapshot(nested);expect(JSON.stringify(snapshot)).not.toContain('privateEmail');expect(JSON.stringify(snapshot)).not.toContain('privateToken');expect(validatePlan(snapshot)).toBe(true)})
 it('omits private notes and unknown fields by default',()=>{const snapshot=publicSnapshot({...plan,accountEmail:'private@example.test'} as Plan);expect(snapshot.stops[0].note).toBe('');expect(JSON.stringify(snapshot)).not.toContain('accountEmail');expect(validatePlan(snapshot)).toBe(true);expect(publicSnapshot(plan,true).stops[0].note).toBe('내 예약번호 12345')})
 it('does not expose management keys in view links or snapshots',()=>{const input=createShareInput(plan,false);expect(input.managementKey).toMatch(/^[\w-]{43}$/);expect(input.requestId).toMatch(/^[\da-f-]{36}$/);expect(JSON.stringify(input.plan)).not.toContain(input.managementKey);expect(shareStorageKey('guest')).not.toBe(shareStorageKey('member:1'))})
 it('drops executable, protocol-relative, credentialed and malformed links',()=>{for(const url of ['javascript:alert(1)','//evil.test/','https://me:secret@example.test','/account','https://example.test\\@evil.test'])expect(safeShareUrl(url)).toBe('');expect(safeShareUrl('https://example.test/info')).toBe('https://example.test/info');expect(safeShareUrl('/discover/239')).toBe('/discover/239')})
 it('clones a valid independently editable itinerary with fresh identities',()=>{const clone=copySharedPlan(publicSnapshot(plan));expect(validatePlan(clone)).toBe(true);expect(clone.id).not.toBe(plan.id);expect(clone.stops[0].id).not.toBe(plan.stops[0].id);expect(clone.interests).toEqual(plan.interests);expect(clone.stops[0].note).toBe('');clone.stops[0].name='새 이름';expect(plan.stops[0].name).toBe('긴토키 카페')})
 it('detects shared content changes while ignoring save timestamps and excluded notes',()=>{expect(shareSignature(plan,false)).toBe(shareSignature({...plan,updatedAt:'2026-10-05T02:00:00Z',stops:[{...plan.stops[0],note:'변경'}]},false));expect(shareSignature(plan,true)).not.toBe(shareSignature({...plan,stops:[{...plan.stops[0],note:'변경'}]},true))})
 it('preserves pending management handles for retry and discards corrupt browser data',()=>{const entry={input:createShareInput(plan,false)};expect(readManagedShares({getItem:()=>JSON.stringify([entry,null,{input:{}}])},'x')).toEqual([entry]);expect(readManagedShares({getItem:()=>'{bad'},'x')).toEqual([])})
})
