const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {harness,nodes,toHtml,root}=require('../v10/source_harness.cjs');const {feed}=require('./fixtures.cjs');const {plan,value,date}=require('../v9/fixtures.cjs');
let n=0;const check=(condition,note)=>{n++;assert.ok(condition,note)};
const app=harness();const view=app.load('frontend/src/features/goods/rankingView.ts');
check(view.isGoodsFeed(feed));
for(const change of [{items:[null]}, {from:'2026-09-16T00:00:00Z'},{basis:'AI_ESTIMATE'},{windowDays:7},{items:[{...feed.items[0],rank:0}]},{items:[{...feed.items[0],eventProductId:-1}]},{from:'not-a-date'}])check(!view.isGoodsFeed({...feed,...change}));
check(view.goodsState(feed.items[5]).includes('품절'));check(view.goodsState(feed.items[4]).includes('종료'));
check(view.carouselEdges(0,300,600).next&&!view.carouselEdges(0,300,600).previous);
check(!view.carouselEdges(300,300,600).next);check(!view.carouselEdges(0,600,300).next);
const carousel=app.load('frontend/src/features/goods/BestsellerCarousel.tsx');
let tree=app.render(carousel.GoodsCarousel,{feed},true),html=toHtml(tree);
check(html.includes('최근 30일'));check(html.includes('POS'));check(html.includes('취소 제외'));
check(nodes(tree).filter(e=>e.type==='li').length===8);check(html.includes('/products/101'));
check(html.includes('달토끼 아크릴 키링'));check(html.includes('현재 품절 표기'));check(html.includes('행사 종료'));
check(nodes(tree).some(e=>e.type==='button'&&e.props['aria-label']==='이전 굿즈 보기'&&e.props.disabled));
const scroll=nodes(tree).find(e=>e.type==='ol');let moves=[];
scroll.props.ref.current={clientWidth:500,scrollBy:x=>moves.push(x)};
scroll.props.onKeyDown({key:'ArrowRight',target:1,currentTarget:1,preventDefault(){}});check(moves[0].left===440);
scroll.props.onKeyDown({key:'ArrowLeft',target:1,currentTarget:1,preventDefault(){}});check(moves[1].left===-440);
scroll.props.onKeyDown({key:'ArrowRight',target:2,currentTarget:1,preventDefault(){}});check(moves.length===2);
const emptyApp=harness({remote:{loading:false,error:null,data:{...feed,items:[]}}});
check(toHtml(emptyApp.render(emptyApp.load('frontend/src/features/goods/BestsellerCarousel.tsx').BestsellerSection,{},true)).includes('아직 집계된'));
const errorApp=harness({remote:{loading:false,error:new Error('mock'),data:null}});check(toHtml(errorApp.render(errorApp.load('frontend/src/features/goods/BestsellerCarousel.tsx').BestsellerSection,{},true)).includes('행사 목록은 계속'));
check(!fs.readFileSync(path.join(root,'frontend/src/features/goods/BestsellerCarousel.tsx'),'utf8').includes('setInterval'));
let opens=0,detailArgs;
const mapProps={plan,participants:value.participants,onOpen(){opens++},day:date,focusParticipantId:1,eventId:'10',assets:[]};
const map=app.load('frontend/src/features/floorplan/InteractiveFloorPlans.tsx').MapView;
tree=app.render(map,mapProps,true);
const canvas=nodes(tree).find(e=>typeof e.type==='function'&&e.type.name==='PlanCanvas');check(!!canvas.props.renderSelection);
const selection=canvas.props.renderSelection(true,(...args)=>{detailArgs=args});
check(toHtml(selection).includes('달토끼공방'));
const open=nodes(selection).find(e=>e.props['data-floorplan-details']===1);open.props.onClick({currentTarget:{isConnected:true}});
check(opens===0);check(detailArgs[1]==='달토끼공방');check(toHtml(detailArgs[0]).includes('이번 행사 상품'));
check(detailArgs[0].props.shareUrl.includes('booth=1'));
const inline=canvas.props.renderSelection(false,()=>{});nodes(inline).find(e=>e.props['data-floorplan-details']===1).props.onClick({currentTarget:{}});check(opens===1);
// Use the actual canvas component and state handlers; no React DOM/effects in this harness.
const canvasApp=harness();const Canvas=canvasApp.load('frontend/src/features/floorplan/PlanCanvas.tsx').PlanCanvas;
let show;const props={...canvas.props,renderSelection:(expanded,fn)=>{show=fn;return '선택 부스 상품 보기'}};
let c=canvasApp.render(Canvas,props,true);
nodes(c).find(e=>e.type==='button'&&toHtml(e.props.children)==='배치도 전체화면').props.onClick();
c=canvasApp.render(Canvas,props);check(c.type==='dialog');check(toHtml(c).includes('선택 부스 상품 보기'));
show('가상 상품 상세','달토끼공방',{isConnected:true});c=canvasApp.render(Canvas,props);
check(c.type==='dialog');check(nodes(c).filter(e=>e.type==='dialog').length===1);check(toHtml(c).includes('같은 지도 위치로 돌아가기'));
check(nodes(c).find(e=>e.props.className==='floorplan-full-map').props.inert===true);
c.props.onCancel({preventDefault(){}});c=canvasApp.render(Canvas,props);check(c.type==='dialog');check(!toHtml(c).includes('가상 상품 상세'));
c.props.onCancel({preventDefault(){}});c=canvasApp.render(Canvas,props);check(c.type!=='dialog');
console.log(`PASS: v11 ${n} actual source UI/ranking checks (hook harness, not React DOM).`);
