// Generated by scripts/sync-taxonomy.py.
export type EventType = 'COMIC_DOUJIN' | 'DOLL' | 'ONLY_EVENT' | 'BIRTHDAY_CAFE' | 'STATIONERY_GOODS' | 'SUBCULTURE_MUSIC' | 'ANIME_GAME_FESTIVAL' | 'ART_BOOK' | 'BOARD_GAME' | 'CHARACTER_ART' | 'ILLUSTRATION' | 'FAN_CAFE' | 'POPUP_STORE' | 'CARD_COLLECTIBLES' | 'FAN_CONVENTION' | 'WINE' | 'WEDDING' | 'LIFESTYLE' | 'DESIGN' | 'BUSINESS' | 'WALK' | 'LIGHT' | 'MUSIC' | 'FOOD' | 'CULTURE' | 'CONCERT' | 'MUSIC_FESTIVAL'
export interface TaxonomyOption { code: string; label: string; types: string[]; subjects: string[]; works: string[] }
export interface TaxonomyField { key: 'subculture' | 'exhibitions' | 'festivals'; code: 'SUBCULTURE' | 'EXHIBITION' | 'FESTIVAL'; label: string; types: { code: EventType; label: string }[]; formats: TaxonomyOption[]; topics: TaxonomyOption[] }
export const taxonomy: { version: number; fields: TaxonomyField[] }
