/* Fabricated UX fixture only. Do not import into the service database. */
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'../..')
const read=f=>JSON.parse(fs.readFileSync(path.join(root,'collector/examples/v5',f+'.json')))
const e=read('events').events[0],p=read('participants').participants[0],s=read('sales').sales,baseProduct=s.products[0]
const date='2026-10-11';const event={...e,name:'[DEMO] 가을의 작은 창작 마켓',description:'개별 작가들의 그림과 문구, 캐릭터 소품을 만나는 가상의 화면 검증 행사입니다. 실제 개최하는 행사가 아닙니다.',venueName:'가상 전시장',address:null,admission:'가상 안내 · 입장 조건은 공식 주최 공지에서 확인',warnings:[],occurrences:[{startDate:'2026-10-10',endDate:'2026-10-11',startTime:'11:00',endTime:'17:00'},{startDate:'2026-10-13',endDate:'2026-10-13',startTime:'12:00',endTime:'17:00'}],sources:[{url:'https://example.com/demo-only',kind:'OFFICIAL',access:'ORIGINAL',evidence:'가상 데이터'}],operationStatus:{state:'SCHEDULED',note:'[DEMO] 디자인 확인용 예시입니다.',sourceUrl:'https://example.com/demo-only',checkedOn:'2026-09-17'},discoveryLinks:[]}
const names=['달토끼공방','별빛 문방구','작은 파도 스튜디오','구름 속 산책','몽글 인형방','소소한 기록']
const participants=names.map((name,i)=>({id:i+1,participant:{...p,registrationName:name,locations:[{code:`B${i+1}`,status:'ASSIGNED',hall:'1관',zone:null,startDate:date,endDate:date,floorPlanUrl:null}],members:[{name,kind:'CIRCLE',aliases:[],profileUrl:null}],subjects:i===0?['달토끼','캐릭터 문구']:['일러스트','문구']},sales:{...s,summary:i===0?'달토끼 캐릭터의 키링과 스티커를 소개해요.':'독립 작가의 일러스트 문구·작은 소품을 소개해요.',evidenceScope:'EVENT_LISTED',warnings:[],products:[{...baseProduct,name:'달토끼 아크릴 키링',summary:'가상의 상품 설명입니다.',evidenceScope:'EVENT_LISTED',saleState:i===1?'SOLD_OUT':'PLANNED',warnings:[],images:[],price:{amount:'8000',currency:'KRW',checkedOn:'2026-09-17',note:'가상 표시금액'}},{...baseProduct,name:'달토끼 스티커 팩',summary:'가상 상시 상품 참고입니다. 이번 행사 판매는 미확인입니다.',evidenceScope:'GENERAL_CATALOG',saleState:'UNKNOWN',images:[],warnings:[],price:null}]}}))
const shapes=[]
for(let y=0;y<12;y++)for(let x=0;x<24;x++) {const i=y*24+x+1,left=.035+x*.039,top=.04+y*.074;shapes.push({id:'shape-'+i,label:'B'+i,points:[{x:left,y:top},{x:left+.028,y:top},{x:left+.028,y:top+.052},{x:left,y:top+.052}],status:i<=6?'MATCHED':'UNMAPPED',links:i<=6?[{participantId:i,dates:[date],method:'AUTO'}]:[],issues:[]})}
const plan={id:'demo-plan',assetId:12,state:'READY',scope:{title:'[DEMO] 1관 부스 배치',hall:'1관',zone:null,dates:[date]},publishedAt:'2026-09-17T00:00:00Z',sourceUrl:'https://example.com/demo-only',credit:'가상 도면 · 실제 행사 아님',width:1800,height:1000,imageUrl:null,shapes,partial:true}
const value={id:10,mode:'INFO_ONLY',event,participants,assets:[],banner:null,publishedAt:'2026-09-17T00:00:00Z'}
module.exports={value,plan,date}
