import { useState,type FormEvent } from 'react'
import { api } from '../../api/client'
import { useRemote } from '../../app/useRemote'
import { ErrorState,LoadingState } from '../../components/ui/States'
import type { Subject } from './api'
import './subculture.css'
type Row=Subject&{active:boolean;aliasesJson?:string}
type Relation={id:string;revision:number;subjectId:string;kind:'EVENT'|'PRODUCT'|'CREATOR';targetId:number;eventId:number|null;participantId:number|null;sourceUrl:string;evidence:string;active:boolean}
const emptySubject=():Row=>({id:crypto.randomUUID(),revision:0,kind:'WORK',name:'',workId:null,workName:null,medium:'게임',sourceUrl:'',active:true,aliasesJson:'[]'})
export function SubjectAdmin(){
 const list=useRemote("features/subculture/SubjectAdmin:SubjectAdmin:list", ()=>api<Row[]>('/api/admin/subculture/subjects',{cache:'no-store'}),[]),[draft,setDraft]=useState(emptySubject),[subjectId,setSubjectId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const links=useRemote("features/subculture/SubjectAdmin:SubjectAdmin:links", ()=>subjectId?api<Relation[]>(`/api/admin/subculture/subjects/${subjectId}/links`,{cache:'no-store'}):Promise.resolve([]),[subjectId])
 const blank=():Relation=>({id:crypto.randomUUID(),revision:0,subjectId,kind:'EVENT',targetId:0,eventId:null,participantId:null,sourceUrl:'',evidence:'',active:true})
 const [relation,setRelation]=useState<Relation|null>(null)
 async function saveSubject(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await api('/api/admin/subculture/subjects/'+draft.id,{method:'PUT',body:JSON.stringify({...draft,aliases:JSON.parse(draft.aliasesJson||'[]')})});await list.reload();setSubjectId(draft.id);setDraft(emptySubject());}catch(e){setError(e instanceof Error?e.message:'저장 실패')}finally{setBusy(false)}}
 async function saveLink(e:FormEvent){e.preventDefault();if(!relation||busy)return;setBusy(true);setError('');try{await api('/api/admin/subculture/subject-links/'+relation.id,{method:'PUT',body:JSON.stringify(relation)});setRelation(null);await links.reload();}catch(e){setError(e instanceof Error?e.message:'저장 실패')}finally{setBusy(false)}}
 return <section className="sc-live sc-live-settings"><h1>작품·캐릭터와 공개 정보 연결</h1><p>기존 행사·상품·작가 ID를 사용합니다. 공식 출처와 연결 근거를 확인한 항목만 등록하세요. 미검토 수집 키워드를 자동 공개하지 않습니다.</p>{error&&<p role="alert">{error}</p>}
 {list.loading?<LoadingState/>:list.error?<ErrorState error={list.error} retry={()=>void list.reload()}/>:<><label className="field">기존 항목 수정<select value={draft.id} onChange={e=>{const row=list.data?.find(r=>r.id===e.target.value);if(row)setDraft(row)}}><option value={draft.id}>새 항목 또는 현재 편집 항목</option>{list.data?.map(r=><option key={r.id} value={r.id}>{r.name} · {r.kind} {!r.active?'· 비공개':''}</option>)}</select></label><button type="button" className="btn secondary" onClick={()=>setDraft(emptySubject())}>새 항목</button></>}
 <form className="sc-live-custom" onSubmit={saveSubject}><h2>작품·캐릭터 검토</h2><label>종류<select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as Row['kind'],workId:null,medium:e.target.value==='WORK'?'게임':''})}><option value="WORK">작품</option><option value="CHARACTER">캐릭터</option></select></label><label>이름<input required maxLength={160} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>{draft.kind==='WORK'?<label>작품 종류<select value={draft.medium} onChange={e=>setDraft({...draft,medium:e.target.value})}>{['게임','애니메이션','만화·웹툰','소설','오리지널·기타'].map(v=><option key={v}>{v}</option>)}</select></label>:<label>출처 작품<select required value={draft.workId||''} onChange={e=>setDraft({...draft,workId:e.target.value||null})}><option value="">작품 선택</option>{list.data?.filter(r=>r.kind==='WORK'&&r.active).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}<label>공식 근거 URL<input required type="url" value={draft.sourceUrl} onChange={e=>setDraft({...draft,sourceUrl:e.target.value})}/></label><label><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>공개</label><button className="btn primary" disabled={busy}>검토한 항목 저장</button></form>
 <label className="field">연결할 작품·캐릭터<select value={subjectId} onChange={e=>{setSubjectId(e.target.value);setRelation(null)}}><option value="">항목 선택</option>{list.data?.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
 {subjectId&&<><button className="btn secondary" onClick={()=>setRelation(blank())}>검토한 연결 추가</button>{links.error&&<ErrorState error={links.error} retry={()=>void links.reload()}/>}<ul>{links.data?.map(l=><li key={l.id}>{l.kind} · {l.targetId} · {l.active?'공개':'비공개'} <button className="btn secondary" onClick={()=>setRelation(l)}>수정·공개 해제</button></li>)}</ul></>}
 {relation&&<form className="sc-live-custom" onSubmit={saveLink}><h2>연결 근거</h2><label>관계<select value={relation.kind} onChange={e=>setRelation({...relation,kind:e.target.value as Relation['kind'],targetId:0,eventId:null,participantId:null})}><option value="EVENT">관련 행사</option><option value="PRODUCT">해당 캐릭터의 상품</option><option value="CREATOR">작가의 해당 캐릭터 작업 이력</option></select></label><label>기존 대상 ID<input required type="number" min={1} value={relation.targetId||''} onChange={e=>setRelation({...relation,targetId:Number(e.target.value),eventId:relation.kind==='EVENT'?Number(e.target.value):relation.eventId})}/></label>{relation.kind==='PRODUCT'&&<><label>행사 ID<input required type="number" min={1} value={relation.eventId||''} onChange={e=>setRelation({...relation,eventId:Number(e.target.value)})}/></label><label>참가 부스 ID<input required type="number" min={1} value={relation.participantId||''} onChange={e=>setRelation({...relation,participantId:Number(e.target.value)})}/></label></>}<label>근거 URL<input required type="url" value={relation.sourceUrl} onChange={e=>setRelation({...relation,sourceUrl:e.target.value})}/></label><label>확인한 내용<textarea required maxLength={1000} value={relation.evidence} onChange={e=>setRelation({...relation,evidence:e.target.value})}/></label><label><input type="checkbox" checked={relation.active} onChange={e=>setRelation({...relation,active:e.target.checked})}/>공개</label><p>작가의 작업 이력은 이번 행사 판매를 의미하지 않습니다. 상품 연결은 기존 판매 근거·상태를 함께 확인합니다.</p><button className="btn primary" disabled={busy}>검토한 연결 저장</button></form>}
 </section>
}
