import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import vm from 'node:vm'
import {buildPackage,liveMedia,usable,TTL,MAX_IMAGES,apiOrigin,safeLink} from '../../frontend/public/offline/policy.mjs'
import {boundedFetch} from '../../frontend/public/offline/store.mjs'
import {pageMetadata} from '../../frontend/seo/metadata.mjs'
const raw=()=>({id:1,publishedAt:'2026-09-18',event:{region:'GYEONGGI',subcategory:'DESIGN',name:'테스트 행사',venueName:'킨텍스',sources:[{url:'https://example.com'}],privateNote:'SECRET'},participants:[{id:10,participant:{registrationName:'테스트 부스',locations:[{code:'A1',startDate:'2026-10-10',endDate:'2026-10-10'}],officialLinks:['https://example.com'],privateNote:'SECRET'},productRows:[{id:20,data:{name:'키링',evidenceScope:'EVENT_SALE_CONFIRMED',price:{amount:'5000',currency:'KRW',checkedOn:'2026-09-18'},images:[{imageUrl:'https://raw.example.com/forbidden'}],note:'SECRET'},verification:{state:'NOT_RECONFIRMED'}}]}],assets:[{id:30,type:'PRODUCT',participantId:10,productId:20,offlineAllowed:true,url:'https://cdn.example.com/a.png',credit:'작가',attribution:'https://example.com'}],privateNote:'SECRET'})
const plans=()=>({managedAssetIds:[40],plans:[{id:'version-a',assetId:40,state:'READY',offlineAllowed:true,imageUrl:'https://cdn.example.com/plan.png',scope:{title:'A홀',dates:['2026-10-10'],hall:'A'},credit:'주최',sourceUrl:'https://example.com'}]})
test('explicit public projection excludes notes, orders and raw image candidates',()=>{const p=buildPackage(raw(),plans(),[{type:'PRODUCT',id:20,note:'SECRET'}]);assert.ok(!JSON.stringify(p).includes('SECRET'));assert.ok(!JSON.stringify(p).includes('raw.example'));assert.equal(p.participants[0].products[0].name,'키링');assert.equal(p.participants[0].locations[0].code,'A1')})
test('selected product marks its parent booth without exporting member records',()=>{const p=buildPackage(raw(),plans(),[{type:'PRODUCT',id:20}]);assert.equal(p.participants[0].selected,true);assert.equal(p.participants[0].products[0].selected,true);assert.equal(p.participants[0].products[0].verification,'NOT_RECONFIRMED')})
test('no selected item exports no implicit account selection',()=>{const p=buildPackage(raw(),plans());assert.equal(p.participants[0].selected,false);assert.equal(p.media.length,1)})
test('permissions default denied even if public image URL exists',()=>{const r=raw();delete r.assets[0].offlineAllowed;const p=buildPackage(r,{plans:[]},[{type:'PRODUCT',id:20}]);assert.equal(p.media.length,0);assert.equal(p.noApprovedPlan,true)})
test('managed stale floor plan does not fall back to a permitted raw image',()=>{const r=raw();r.assets.push({id:40,type:'FLOOR_PLAN',offlineAllowed:true,url:'https://cdn.example.com/raw.png'});const f=plans();f.plans[0].state='ROSTER_CHANGED';assert.equal(liveMedia(r,f).filter(x=>x.type==='FLOOR_PLAN').length,0)})
test('managed plan needs both READY and explicit offline permission',()=>{for(const allowed of [false,undefined]){const f=plans();f.plans[0].offlineAllowed=allowed;assert.equal(liveMedia(raw(),f).filter(x=>x.type==='FLOOR_PLAN').length,0)}})
test('image count is limited with explicit omitted count; plan prioritized',()=>{const r=raw();r.assets=Array.from({length:40},(_,i)=>({...r.assets[0],id:i+100}));const p=buildPackage(r,plans(),[{type:'PRODUCT',id:20}]);assert.equal(p.media.length,MAX_IMAGES);assert.equal(p.omittedImages,17);assert.equal(p.media[0].type,'FLOOR_PLAN')})
test('package expires after seven days and has no implicit age renewal',()=>{const p=buildPackage(raw(),plans(),[],'2026-10-10',10000);assert.equal(p.expiresAt,10000+TTL);assert.equal(usable(p,10001),true);assert.equal(usable(p,10000+TTL),false);assert.equal(usable({...p,expiresAt:p.expiresAt+1},10001),false)})
test('unknown/out of scope geography and invalid identifiers rejected',()=>{for(const region of ['INCHEON','OTHER','UNKNOWN'])assert.throws(()=>buildPackage({...raw(),event:{...raw().event,region}},plans()));for(const id of [-1,'1',NaN])assert.throws(()=>buildPackage({...raw(),id},plans()))})
test('local testing API only accepts explicit loopback; production requires HTTPS origin',()=>{assert.equal(apiOrigin('http://localhost:8080'),'http://localhost:8080');assert.equal(apiOrigin('https://api.example.com'),'https://api.example.com');for(const u of ['http://example.com','https://u:p@example.com','file:///x','https://example.com/api','https://example.com/?url=x'])assert.throws(()=>apiOrigin(u));for(const u of ['javascript:alert(1)','data:text/html,x','https://a:b@example.com'])assert.equal(safeLink(u),'')})
test('legacy public products retained as non-linkable items',()=>{const r=raw();r.participants[0].sales={products:[{name:'과거 호환 상품'}]};delete r.participants[0].productRows;const p=buildPackage(r,plans());assert.equal(p.participants[0].products[0].name,'과거 호환 상품');assert.equal(p.participants[0].products[0].id,null)})
test('unknown product property never becomes executable HTML',()=>{const r=raw();r.event.name='<script>alert(1)</script>';assert.equal(buildPackage(r,plans()).name,r.event.name) /* Renderer uses textContent; do not destroy legitimate literal text. */})
test('all three category pages have canonical metadata, unknown category noindex',()=>{for(const category of ['subculture','exhibitions','festivals']){const m=pageMetadata({path:'/discover',search:'?category='+category,siteUrl:'https://example.com'});assert.equal(m.robots,'index,follow');assert.ok(m.canonical.startsWith('https://example.com/discover'))}assert.equal(pageMetadata({path:'/discover',search:'?category=bad',siteUrl:'https://example.com'}).robots,'noindex,follow')})
test('bounded fetch omits credentials, rejects redirect/HTTP/invalid MIME/oversize',async()=>{
 const saved=globalThis.fetch;try{let options;globalThis.fetch=async(_u,o)=>{options=o;return new Response('{"ok":true}',{headers:{'Content-Type':'application/json'}})};assert.deepEqual(await boundedFetch('https://example.com',32),{ok:true});assert.equal(options.credentials,'omit');assert.equal(options.redirect,'error');assert.equal(options.cache,'no-store')
 for(const response of [new Response('oops',{status:404}),new Response('{}',{headers:{'Content-Type':'text/html'}}),new Response('{}',{headers:{'Content-Type':'application/json','Content-Length':'1000'}}),new Response('x'.repeat(40),{headers:{'Content-Type':'application/json'}})]){globalThis.fetch=async()=>response;await assert.rejects(()=>boundedFetch('https://example.com',32))}
 globalThis.fetch=async()=>new Response('<svg/>',{headers:{'Content-Type':'image/svg+xml'}});await assert.rejects(()=>boundedFetch('https://example.com',32,'image'))
 }finally{globalThis.fetch=saved}
})
async function worker(fail=''){
 const handlers={},storage=new Map(),requested=[];const cache={async put(u,r){storage.set(typeof u==='string'?u:u.url,r)},async match(u){return storage.get(typeof u==='string'?u:u.url)}}
 const source=await readFile(new URL('../../frontend/public/offline/sw.js',import.meta.url),'utf8')
 class RelativeRequest extends Request{constructor(url,init){super(new URL(url,'https://example.com'),init)}}
 const self={location:{origin:'https://example.com'},addEventListener(n,fn){handlers[n]=fn},async skipWaiting(){},clients:{async claim(){}}}
 const context={self,URL,Request:RelativeRequest,fetch:async r=>{requested.push(r);const path=new URL(r.url).pathname;const type=path.endsWith('.mjs')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.html')?'text/html':path.endsWith('.svg')?'image/svg+xml':'application/manifest+json';return new Response(path.endsWith('.html')?'<script src="/offline/app.mjs"></script>':r.url,{status:r.url.endsWith(fail)&&fail?404:200,headers:{'Content-Type':type}})},caches:{async open(){return cache},async keys(){return ['boothhana-offline-shell-old','OTHER-PRIVATE-CACHE']},async delete(n){requested.push(n)}}}
 vm.runInNewContext(source,context);return{handlers,storage,requested}
}
test('actual service worker only precaches seven isolated public static files',async()=>{const w=await worker();let pending;w.handlers.install({waitUntil:p=>pending=p});await pending;assert.equal(w.storage.size,7);assert.ok([...w.storage.keys()].every(x=>x.startsWith('/offline/')));for(const r of w.requested){assert.equal(r.credentials,'omit');assert.equal(r.redirect,'error')}})
test('actual service worker install rejects missing shell file',async()=>{const w=await worker('app.mjs');let pending;w.handlers.install({waitUntil:p=>pending=p});await assert.rejects(pending)})
test('actual service worker ignores API, auth, admin, foreign origin, POST requests',async()=>{const w=await worker();for(const [u,method] of [['/api/public/catalog/events/1','GET'],['/api/me','GET'],['/admin','GET'],['/discover/1','GET'],['https://other.example/offline/app.mjs','GET'],['/offline/index.html','POST']]){let responded=false;w.handlers.fetch({request:new Request(new URL(u,'https://example.com'),{method}),respondWith(){responded=true}});assert.equal(responded,false,u)}})
test('worker activation only removes its own old namespace',async()=>{const w=await worker();let pending;w.handlers.activate({waitUntil:p=>pending=p});await pending;assert.deepEqual(w.requested,['boothhana-offline-shell-old'])})
