import { useState,type FormEvent } from 'react'
import { Link,useSearchParams } from 'react-router'
import { useRemote } from '../../app/useRemote'
import { ErrorState,LoadingState } from '../../components/ui/States'
import { ownershipApi,type SeriesLink } from './ownershipApi'
export function AdminSeries(){
 const [params,setParams]=useSearchParams(),event=Number(params.get('event'))
 const [input,setInput]=useState(params.get('event')??'')
 return <section className="support-page"><h1>행사 시리즈·회차 연결</h1><p>이름이 같아도 자동 병합하지 않습니다. 주최자·지역·공식 공지를 확인하고 연결하세요. 이 연결은 관리권이나 주최자 확인을 다른 회차에 부여하지 않습니다.</p><form className="support-controls" onSubmit={e=>{e.preventDefault();setParams({event:input})}}><label className="field"><span>행사 번호 (상세 주소의 숫자)</span><input className="input" type="number" min="1" required value={input} onChange={e=>setInput(e.target.value)}/></label><button className="btn primary">행사 불러오기</button></form>{event>0&&<SeriesEditor key={event} event={event}/>}</section>
}
function SeriesEditor({event}:{event:number}){
 const list=useRemote("features/support/AdminSeries:SeriesEditor:list", ownershipApi.series,[]),link=useRemote("features/support/AdminSeries:SeriesEditor:link", ()=>ownershipApi.seriesLink(event),[event])
 const [q,setQ]=useState(''),[query,setQuery]=useState('')
 const candidates=useRemote("features/support/AdminSeries:SeriesEditor:candidates", ()=>query?ownershipApi.candidates(event,query):Promise.resolve([]),[event,query])
 return <><Link to={`/discover/${event}`} target="_blank">공개 행사 #{event} 확인 ↗</Link>{list.loading||link.loading?<LoadingState/>:list.error||link.error?<ErrorState error={list.error||link.error!} retry={()=>{void list.reload();void link.reload()}}/>:link.data&&<SeriesForm key={link.data.revision} event={event} value={link.data} list={list.data??[]} saved={x=>{link.setData(x);void list.reload()}}/>}<section className="panel"><h2>다른 회차 후보 찾기</h2><p>후보일 뿐입니다. 공식 출처 확인 후 각 행사를 같은 시리즈로 연결하세요.</p><form onSubmit={e=>{e.preventDefault();setQuery(q)}}><label className="field"><span>공통 행사명</span><input className="input" minLength={2} maxLength={100} required value={q} onChange={e=>setQ(e.target.value)}/></label><button className="btn secondary">후보 검색</button></form>{candidates.error&&<ErrorState error={candidates.error} retry={()=>void candidates.reload()}/>}<p>최대 50건 · 같은 행사 분야에서 검색합니다.</p>{candidates.data?.map(x=><article key={x.id}><Link to={`/admin/event-series?event=${x.id}`}>{x.name}</Link><p>{x.startsOn} · {x.venueName} · {x.seriesId?`시리즈 #${x.seriesId}`:'미연결'}</p><Link to={`/admin/subculture?event=${x.id}`} target="_blank">수집 원문·주최자 확인</Link></article>)}</section></>
}
function SeriesForm({event,value,list,saved}:{event:number;value:SeriesLink;list:{id:number;name:string;officialUrl:string}[];saved:(v:SeriesLink)=>void}){
 const [selected,setSelected]=useState(String(value.seriesId??'')),[name,setName]=useState(''),[url,setUrl]=useState(''),[edition,setEdition]=useState(value.edition),[evidence,setEvidence]=useState(value.evidenceUrl??''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{saved(await ownershipApi.saveSeries(event,{revision:value.revision,seriesId:selected&&selected!=='new'?Number(selected):null,name:selected==='new'?name:'',officialUrl:url,edition,evidenceUrl:evidence,note}))}catch(e){setError(e instanceof Error?e.message:'저장 실패')}finally{setBusy(false)}}
 return <form className="panel support-form" onSubmit={e=>void submit(e)}><fieldset disabled={busy}><label className="field"><span>시리즈</span><select className="select" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">연결 없음 / 연결 해제</option><option value="new">새 시리즈 만들기</option>{list.map(s=><option key={s.id} value={s.id}>{s.name} · #{s.id}</option>)}</select></label>{selected==='new'&&<><label className="field"><span>시리즈 이름</span><input className="input" required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>시리즈 공식 주소</span><input className="input" type="url" required maxLength={2048} value={url} onChange={e=>setUrl(e.target.value)}/></label></>}<label className="field"><span>회차 표시 (예: 41회 / 2026 가을)</span><input className="input" maxLength={160} value={edition} onChange={e=>setEdition(e.target.value)}/></label><label className="field"><span>연결 또는 해제 확인 근거 URL</span><input className="input" type="url" required maxLength={2048} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><label className="field"><span>주최자·장소·회차 확인 결과 / 해제 사유</span><textarea className="textarea" required maxLength={4000} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="btn primary">회차 연결 저장</button></fieldset></form>
}
