import { useState,type FormEvent } from 'react'
import { Link } from 'react-router'
import { useRemote } from '../../app/useRemote'
import { ErrorState,LoadingState } from '../../components/ui/States'
import { ownershipApi,type OwnerProducts as Products } from './ownershipApi'
import type { ProductRow } from '../catalog/api'
import { useUnsaved } from './useSupportUnsaved'
export function OwnerProducts({event,participant}:{event:number;participant:number}){
 const [selected,setSelected]=useState<number|null>(null),[done,setDone]=useState(false)
 const state=useRemote(()=>ownershipApi.products(event,participant),[event,participant])
 return <section className="content-wrap section-pad support-page"><Link to="/support/management">← 관리 목록</Link><h1>부스 상품 관리</h1><p>현재 공개된 본인 단독 부스 상품만 수정할 수 있습니다. 공동 부스·새 상품·이미지는 근거를 첨부한 정정 요청을 이용하세요. 상품 연결·행사 참가 근거는 변경하지 않습니다.</p>{state.loading?<LoadingState/>:state.error?<ErrorState error={state.error} retry={()=>void state.reload()}/>:state.data&&<>{!state.data.items.length&&<p>공개 상품이 없습니다.</p>}{done&&<p role="status">상품 정보를 수정했습니다.</p>}{selected===null?state.data.items.filter(p=>p.id!=null).map(p=><article className="panel" key={p.id}><h2>{p.data.name}</h2><button className="btn secondary" onClick={()=>{setSelected(p.id!);setDone(false)}}>상품 수정</button></article>):state.data.items.filter(p=>p.id===selected).map(p=><ProductForm key={`${p.id}:${state.data!.revision}`} event={event} participant={participant} row={p} revision={state.data!.revision} saved={next=>{state.setData(next);setSelected(null);setDone(true)}}/>)}</>}</section>
}
function ProductForm({event,participant,row,revision,saved}:{event:number;participant:number;row:ProductRow;revision:number;saved:(v:Products)=>void}){
 const [name,setName]=useState(row.data.name),[summary,setSummary]=useState(row.data.summary),[amount,setAmount]=useState(row.data.price?.amount??''),[currency,setCurrency]=useState(row.data.price?.currency??'KRW'),[saleState,setSaleState]=useState(row.data.saleState),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const clear=useUnsaved(!busy&&(name!==row.data.name||summary!==row.data.summary||amount!==(row.data.price?.amount??'')||currency!==(row.data.price?.currency??'KRW')||saleState!==row.data.saleState||!!note))
 const send=async(e:FormEvent)=>{e.preventDefault();if(busy||row.id==null)return;setBusy(true);setError('');try{const next=await ownershipApi.editProduct(event,participant,row.id,{revision,name,summary,amount,currency,saleState,note});clear();saved(next)}catch(e){setError(e instanceof Error?e.message:'저장 실패')}finally{setBusy(false)}}
 return <form className="panel support-form" onSubmit={e=>void send(e)}><h2>{row.data.name}</h2><fieldset disabled={busy}><label className="field"><span>상품명</span><input className="input" required maxLength={255} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>상품 설명</span><textarea className="textarea" maxLength={1000} value={summary} onChange={e=>setSummary(e.target.value)}/></label><label className="field"><span>가격 (미정이면 비워두세요)</span><input className="input" inputMode="decimal" pattern="[0-9]{1,12}(\.[0-9]{1,2})?" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field"><span>통화</span><input className="input" required pattern="[A-Z]{3}" maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value)}/></label><label className="field"><span>판매 상태</span><select className="select" value={saleState} onChange={e=>setSaleState(e.target.value)}>{Object.entries({PLANNED:'판매 예정',ON_SALE:'판매 중',SOLD_OUT:'품절',CANCELED:'판매 취소',UNKNOWN:'미확인'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field"><span>변경 사유</span><input className="input" required maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="btn primary">상품 수정 저장</button></fieldset></form>
}
