import { OwnerProducts } from './OwnerProducts'
import { useState,type FormEvent } from 'react'
import { Link,useSearchParams } from 'react-router'
import { useAuth } from '../../app/useAuth'
import { useRemote } from '../../app/useRemote'
import { ErrorState,LoadingState,EmptyState } from '../../components/ui/States'
import { ownershipApi,type OwnerValue } from './ownershipApi'
import { supportApi } from './api'
import { supportPath } from './rules'
import { useUnsaved } from './useSupportUnsaved'
export function OwnershipManagement(){
 const {user,loading,loginUrl}=useAuth(),[params]=useSearchParams()
 const events=useRemote(()=>user?ownershipApi.events():Promise.resolve([]),[user?.id]),booths=useRemote(()=>user?supportApi.managed():Promise.resolve([]),[user?.id])
 if(loading)return <LoadingState/>
 if(!user)return <EmptyState title="로그인 후 관리할 수 있어요" description="인증 신청한 계정으로 로그인해 주세요." action={<a href={loginUrl}>카카오 로그인</a>}/>
 const event=Number(params.get('event')),participant=Number(params.get('participant')||0),type=params.get('type')||'EVENT'
 if(event>0&&type==='PRODUCTS')return <OwnerProducts key={`${event}:${participant}`} event={event} participant={participant}/>
 if(event>0)return <OwnerEditor key={`${event}:${participant}:${type}`} event={event} participant={participant} type={type}/>
 return <section className="content-wrap section-pad support-page"><h1>내 행사·부스 관리</h1><p>사용자에게 공개된 행사·부스를 관리합니다. 승인된 대상과 회차만 수정할 수 있습니다. 입장권·프로그램·FAQ 변경안은 관리자 검토 후 공개합니다.</p><Link to="/support?kind=CLAIM">인증 신청·보완·처리 내역</Link>{events.loading||booths.loading?<LoadingState/>:events.error||booths.error?<ErrorState error={events.error||booths.error!} retry={()=>{void events.reload();void booths.reload()}}/>:<><h2>주최 행사</h2>{!events.data?.length&&<p>연결된 행사가 없습니다. 행사 상세에서 주최자 확인을 신청해 주세요.</p>}{events.data?.map(e=><article className="panel" key={e.eventId}><h3>{e.name}</h3><p>{e.organizerName} · {e.state==='ACTIVE'?'주최자 확인':'관리권 회수'}</p><div className="row-actions"><Link to={`/discover/${e.eventId}`}>행사 보기</Link><Link to={`/support/tickets/${e.claimId}`}>신청 내역</Link>{e.state==='ACTIVE'&&<><Link to={`?event=${e.eventId}&type=EVENT`}>행사 정보 수정</Link><Link to={supportPath('REPORT',{namespace:'CATALOG',type:'EVENT',eventId:e.eventId,id:e.eventId})+'&category=OTHER&template=VISITOR_GUIDE'}>입장권·프로그램·FAQ 변경 요청</Link></>}</div></article>)}<h2>운영 부스</h2>{!booths.data?.length&&<p>연결된 부스가 없습니다.</p>}{booths.data?.map(b=><article className="panel" key={b.exhibitorId}><h3>{b.name}</h3><p>{b.state==='ACTIVE'?(b.permission==='CATALOG_EDIT'?'운영자 확인':'정정 요청 관계 확인 (직접 편집은 재인증 필요)'):'관리권 회수'}</p><Link to={`/support/tickets/${b.claimId}`}>신청 내역</Link>{b.state==='ACTIVE'&&b.participants.map(p=><div className="support-ticket-row" key={p.id}><Link to={p.route}>{p.name}</Link><div className="row-actions">{p.editCapabilities?.participant&&<><Link to={`?event=${p.eventId}&participant=${p.id}&type=PARTICIPANT`}>부스 소개 수정</Link>{p.editCapabilities?.sales&&<Link to={`?event=${p.eventId}&participant=${p.id}&type=SALES`}>판매 안내 수정</Link>}{p.editCapabilities?.products&&<Link to={`?event=${p.eventId}&participant=${p.id}&type=PRODUCTS`}>상품 수정</Link>}</>}{p.editCapabilities?.reason&&<p>{p.editCapabilities.reason}</p>}{p.editCapabilities?.participant&&p.editCapabilities.salesReason&&<p>{p.editCapabilities.salesReason}</p>}<Link to={supportPath('REPORT',{namespace:'CATALOG',type:'PARTICIPANT',eventId:p.eventId,id:p.id})}>이미지·상품·공동 부스 정정</Link></div></div>)}</article>)}</>}</section>
}
function OwnerEditor({event,participant,type}:{event:number;participant:number;type:string}){
 const [savedNotice,setSavedNotice]=useState(false)
 const state=useRemote(()=>ownershipApi.editable(event,type,participant),[event,type,participant])
 return <section className="content-wrap section-pad support-page support-narrow"><Link to="/support/management">← 관리 목록</Link><h1>{type==='EVENT'?'행사 정보':type==='SALES'?'판매 안내':'부스 소개'} 수정</h1><p>수집기가 다시 조사해도 직접 수정한 값은 유지됩니다. 이미지·배치도·상품 추가는 권리·참가 범위 확인을 위해 정정 요청으로 접수해 주세요.</p><Link to={supportPath('REPORT',{namespace:'CATALOG',type:participant?'PARTICIPANT':'EVENT',eventId:event,id:participant||event})}>이미지·배치도 등 정정 요청</Link>{savedNotice&&<p role="status">수정했습니다.</p>}{state.loading?<LoadingState/>:state.error||!state.data?<ErrorState error={state.error??new Error('정보 없음')} retry={()=>void state.reload()}/>:<OwnerForm key={state.data.revision} event={event} participant={participant} type={type} value={state.data} saved={next=>{state.setData(next);setSavedNotice(true)}}/>}</section>
}
const labels:Record<string,string>={description:'소개',venueName:'장소명',address:'주소',admission:'입장 안내',summary:'판매 안내',salesMethod:'판매 방식',officialLinks:'공식 링크 (한 줄에 하나)',occurrences:'행사 일시'}
function OwnerForm({event,participant,type,value,saved}:{event:number;participant:number;type:string;value:OwnerValue;saved:(x:OwnerValue)=>void}){
 const keys=type==='EVENT'?['description','venueName','address','admission']:type==='PARTICIPANT'?['description','officialLinks']:['summary','salesMethod']
 const [fields,setFields]=useState<Record<string,string>>(Object.fromEntries(keys.map(k=>[k,Array.isArray(value.data[k])?(value.data[k] as string[]).join('\n'):String(value.data[k]??'')]))),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false)
 const [dates,setDates]=useState((value.data.occurrences??[]) as {startDate:string;endDate:string;startTime:string|null;endTime:string|null}[])
 const [dirty,setDirty]=useState(false),clear=useUnsaved((dirty||!!note)&&!busy)
 const send=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const patch:Record<string,unknown>={};for(const k of keys){const v=k==='officialLinks'?fields[k].split('\n').map(x=>x.trim()).filter(Boolean):fields[k];if(JSON.stringify(v)!==JSON.stringify(value.data[k]??''))patch[k]=v}if(type==='EVENT'&&JSON.stringify(dates)!==JSON.stringify(value.data.occurrences))patch.occurrences=dates;if(!Object.keys(patch).length)throw new Error('변경된 내용이 없습니다.');const result=await ownershipApi.edit(event,type,participant,value.revision,patch,note);clear();setDirty(false);setDone(true);saved(result)}catch(e){setError(e instanceof Error?e.message:'수정 실패')}finally{setBusy(false)}}
 return <form className="panel support-form" onSubmit={e=>void send(e)}><fieldset disabled={busy}>{keys.map(k=><label className="field" key={k}><span>{labels[k]}</span><textarea className="textarea" rows={k==='description'?5:2} maxLength={k==='description'?10000:4000} value={fields[k]} onChange={e=>{setFields({...fields,[k]:e.target.value});setDirty(true)}}/></label>)}{type==='EVENT'&&dates.map((d,i)=><fieldset key={i}><legend>행사 일시 {i+1}</legend>{(['startDate','endDate','startTime','endTime'] as const).map(k=><label className="field" key={k}><span>{{startDate:'시작일',endDate:'종료일',startTime:'시작 시간',endTime:'종료 시간'}[k]}</span><input className="input" type={k.endsWith('Date')?'date':'time'} required={k.endsWith('Date')} value={d[k]??''} onChange={e=>{setDates(dates.map((row,n)=>n===i?{...row,[k]:e.target.value||null}:row));setDirty(true)}}/></label>)}</fieldset>)}<label className="field"><span>변경 사유</span><input className="input" required maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}{done&&<p role="status">수정했습니다.</p>}<button className="btn primary" disabled={busy}>{busy?'저장 중…':'공개 정보 수정'}</button><Link to={`/discover/${event}${participant?`/booths/${participant}`:''}`}>사용자 화면 확인</Link></fieldset></form>
}
