import { PageHeader } from '../../components/layout/PageHeader'
import { creatorCatalogApi } from '../creator/catalogApi'
import { useState,type FormEvent } from 'react'
import { Link } from 'react-router'
import { useRemote } from '../../app/useRemote'
import { ErrorState,LoadingState } from '../../components/ui/States'
import { ownershipApi,type OwnerProducts as Products } from './ownershipApi'
import type { ProductRow } from '../catalog/api'
import { useUnsaved } from './useSupportUnsaved'
import { supportPath } from './rules'
export function OwnerProducts({event,participant}:{event:number;participant:number}){
 const [selected,setSelected]=useState<number|null>(null),[done,setDone]=useState(false)
 const state=useRemote("features/support/OwnerProducts:OwnerProducts:state", ()=>ownershipApi.products(event,participant),[event,participant])
 const requestPath=supportPath('REPORT',{namespace:'CATALOG',type:'PARTICIPANT',eventId:event,id:participant})
 return <section className="ownership-workspace"><nav className="creator-breadcrumb" aria-label="현재 위치"><Link to="/support/management">내 공개 행사·부스</Link><span>/ 상품 관리</span></nav><PageHeader eyebrow="Creator · Products" title="부스 상품 관리"/><p>현재 공개된 본인 단독 부스 상품만 수정할 수 있습니다. 직접 등록한 부스는 새 상품도 바로 추가할 수 있습니다. 수집된 부스의 새 상품·이미지 변경은 아래 버튼으로 요청해 주세요.</p>
 <nav className="row-actions" aria-label="공개 상품 관리 동작">{state.data?.directRegistration?<button className="btn primary" onClick={()=>{setSelected(-1);setDone(false)}}>새 상품 추가</button>:<Link className="btn primary" to={`${requestPath}&category=PRODUCT_PRICE&template=NEW_PRODUCT`}>새 상품 추가 요청</Link>}<Link className="btn secondary" to={`${requestPath}&category=IMAGE_RIGHTS&template=PRODUCT_IMAGE`}>이미지 변경 요청</Link><Link className="btn secondary" to={`/discover/${event}/booths/${participant}`}>사용자 화면 확인</Link><Link to="/support?kind=REPORT">요청 처리 내역</Link></nav>
 {state.loading?<LoadingState/>:state.error?<ErrorState error={state.error} retry={()=>void state.reload()}/>:state.data&&<>{!state.data.items.length&&<p>아직 공개된 상품이 없습니다. 위 버튼으로 첫 상품을 추가해 주세요.</p>}{done&&<p role="status">상품 정보를 저장했습니다.</p>}{selected===-1&&state.data.directRegistration?<ProductForm event={event} participant={participant} row={{id:-1,data:{name:'',summary:'',price:null,saleState:'PLANNED',sourceEntryId:null,memberName:null,categories:[],subjects:[],evidenceScope:'EVENT_LISTED',productUrl:null,sources:[],images:[],warnings:[]}}} revision={state.data.revision} cancel={()=>setSelected(null)} saved={next=>{state.setData({...next,directRegistration:true});setSelected(null);setDone(true)}}/>:selected===null?state.data.items.filter(p=>p.id!=null).map(p=><article className="panel" key={p.id}><h2>{p.data.name}</h2><button className="btn secondary" onClick={()=>{setSelected(p.id!);setDone(false)}}>상품 수정</button></article>):state.data.items.filter(p=>p.id===selected).map(p=><ProductForm key={`${p.id}:${state.data!.revision}`} event={event} participant={participant} row={p} revision={state.data!.revision} cancel={()=>setSelected(null)} saved={next=>{state.setData(next);setSelected(null);setDone(true)}}/>)}</>}</section>
}
function ProductForm({event,participant,row,revision,saved,cancel}:{event:number;participant:number;row:ProductRow;revision:number;saved:(v:Products)=>void;cancel:()=>void}){
 const [name,setName]=useState(row.data.name),[summary,setSummary]=useState(row.data.summary),[amount,setAmount]=useState(row.data.price?.amount??''),[currency,setCurrency]=useState(row.data.price?.currency??'KRW'),[saleState,setSaleState]=useState(row.data.saleState),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const dirty=name!==row.data.name||summary!==row.data.summary||amount!==(row.data.price?.amount??'')||currency!==(row.data.price?.currency??'KRW')||saleState!==row.data.saleState||!!note
 const clear=useUnsaved(!busy&&dirty)
 const send=async(e:FormEvent)=>{e.preventDefault();if(busy||row.id==null)return;setBusy(true);setError('');try{const input={revision,name,summary,amount,currency,saleState,note};const next=row.id===-1?await creatorCatalogApi.addProduct(event,participant,input):await ownershipApi.editProduct(event,participant,row.id,input);clear();saved(next)}catch(e){setError(e instanceof Error?e.message:'저장 실패')}finally{setBusy(false)}}
 return <form className="panel support-form" onSubmit={e=>void send(e)}><h2>{row.id===-1?'새 상품':row.data.name}</h2><fieldset disabled={busy}><label className="field"><span>상품명</span><input className="input" required maxLength={255} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>상품 설명</span><textarea className="textarea" maxLength={1000} value={summary} onChange={e=>setSummary(e.target.value)}/></label><label className="field"><span>가격 (미정이면 비워두세요)</span><input className="input" inputMode="decimal" pattern="[0-9]{1,12}(\.[0-9]{1,2})?" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field"><span>통화</span><input className="input" required pattern="[A-Z]{3}" maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value)}/></label><label className="field"><span>판매 상태</span><select className="select" value={saleState} onChange={e=>setSaleState(e.target.value)}>{Object.entries({PLANNED:'판매 예정',ON_SALE:'판매 중',SOLD_OUT:'품절',CANCELED:'판매 취소',UNKNOWN:'미확인'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field"><span>{row.id===-1?'등록 메모 (선택)':'변경 사유'}</span><input className="input" required={row.id!==-1} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className="row-actions"><button className="btn primary">{row.id===-1?'상품 등록하고 공개':'상품 수정 저장'}</button><button type="button" className="btn secondary" onClick={()=>{if(dirty&&!window.confirm('작성 중인 내용을 버리고 상품 목록으로 돌아갈까요?'))return;clear();cancel()}}>상품 목록으로</button></div></fieldset></form>
}
