import { useRef, useState, type FormEvent } from 'react'
import { Link } from 'react-router'
import { supportApi, type Ticket, type ReplyInput } from './api'
import { categories,kinds,statuses,resolutions,evidenceLines,outcomeTone } from './rules'
import { SafeLink } from '../catalog/Shared'
import { useUnsaved } from './useSupportUnsaved'

export function TicketHeader({ticket}:{ticket:Ticket}){return <header className="support-ticket-header"><span className="eyebrow">{kinds[ticket.kind]} · {ticket.number}</span><h1>{ticket.title}</h1><div className="row-actions"><span className={`chip ${outcomeTone(ticket.status)}`}>{statuses[ticket.status]??ticket.status}</span><span>{categories[ticket.kind][ticket.category]}</span>{ticket.resolution&&<strong>{resolutions[ticket.resolution]??ticket.resolution}</strong>}</div><small>{new Date(ticket.createdAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} 접수</small></header>}
export function TicketContext({ticket}:{ticket:Ticket}){
 const snapshot=ticket.receivedSnapshot as {label?:string;route?:string}
 return <>{ticket.target&&<div className="support-target"><strong>신고·신청 대상 · {snapshot.label??ticket.target.type}</strong><p>{ticket.target.day&&`방문일 ${ticket.target.day} `}{ticket.target.hall&&`· ${ticket.target.hall} `}{ticket.target.areaId&&`· 영역 ${ticket.target.areaId}`}</p>{snapshot.route?.startsWith('/')&&!snapshot.route.startsWith('//')&&<Link to={snapshot.route}>현재 공개 정보 보기 ↗</Link>}</div>}
  {ticket.clientContext.errorCode&&<p>오류 문의 코드: <code>{ticket.clientContext.errorCode}</code></p>}
  <details className="support-evidence"><summary>접수 당시 정보 확인</summary><p>당시 서버가 확인한 정보입니다. 신고자가 보던 화면 버전과 다를 수 있어요.</p>{ticket.clientContext.viewedVersion&&<p>신고자가 본 버전: {ticket.clientContext.viewedVersion}</p>}<pre>{JSON.stringify(ticket.receivedSnapshot,null,2)}</pre></details></>
}
export function MessageThread({ticket}:{ticket:Ticket}){return <section className="support-thread" aria-label="접수·답변 내역"><h2>대화 내역</h2>{ticket.messages.map(m=><article key={m.id} className={`support-message ${m.internal?'is-internal':m.author==='ADMIN'?'is-answer':''}`}><div><strong>{m.internal?'관리자 내부 메모':m.author==='ADMIN'?'부스하나 운영팀':'작성자'}</strong><time>{new Date(m.createdAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</time></div><p>{m.body}</p>{m.evidence.map((url,i)=><p key={i}><SafeLink url={url}>첨부 근거 {i+1}</SafeLink></p>)}</article>)}</section>}
export function ReplyForm({ticket,admin=false,onSend}:{ticket:Ticket;admin?:boolean;onSend:(body:ReplyInput)=>Promise<void>}){
 const [body,setBody]=useState(''),[links,setLinks]=useState(''),[internal,setInternal]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const guard=useRef(false),retry=useRef<{signature:string;id:string}|null>(null)
 useUnsaved(Boolean(body||links)&&!busy)
 if(ticket.status==='CLOSED'||ticket.kind==='CLAIM'&&ticket.status==='RESOLVED')return <p className="support-note">종료된 접수입니다. 추가 요청은 <Link to="/support/new">새 문의</Link>로 알려주세요.</p>
 const send=async(e:FormEvent)=>{e.preventDefault();if(guard.current)return;guard.current=true;setBusy(true);setError('');try{const evidence=evidenceLines(links),content={revision:ticket.revision,body,evidence,internal:admin&&internal},signature=JSON.stringify(content);if(retry.current?.signature!==signature)retry.current={signature,id:crypto.randomUUID()};await onSend({...content,requestId:retry.current.id});setBody('');setLinks('');retry.current=null}catch(e){setError(e instanceof Error?e.message:'답변을 저장하지 못했어요.')}finally{guard.current=false;setBusy(false)}}
 return <form className="panel support-form" onSubmit={e=>void send(e)}><h2>{admin?'답변 작성':'추가 내용 보내기'}</h2>{admin&&<label className="check-field"><input type="checkbox" checked={internal} disabled={busy} onChange={e=>setInternal(e.target.checked)}/> 내부 메모로 저장 — 사용자에게 보이지 않음</label>}{admin&&!internal&&<p className="support-note">아래 내용은 작성자에게 공개됩니다. 문의 답변은 ‘답변 완료’로, 신고 답변은 ‘확인 중’으로 처리됩니다.</p>}<label className="field"><span>{internal?'내부 메모':'내용'}</span><textarea className="textarea" required maxLength={10000} rows={5} value={body} disabled={busy} onChange={e=>setBody(e.target.value)}/></label><label className="field"><span>근거 링크 (선택, 한 줄에 하나·최대 5개)</span><textarea className="textarea" rows={2} value={links} disabled={busy} onChange={e=>setLinks(e.target.value)}/></label>{error&&<p role="alert" className="form-alert">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'저장 중…':internal?'내부 메모 저장':admin?'답변 보내기':'추가 내용 보내기'}</button></form>
}
export function Attachments({ticket,admin=false,enabled=false,reload}:{ticket:Ticket;admin?:boolean;enabled?:boolean;reload:()=>Promise<unknown>}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<File|null>(null),ref=useRef<{file:File;id:string}|null>(null),guard=useRef(false)
 const upload=async()=>{if(!selected||guard.current)return;guard.current=true;setBusy(true);setError('');try{if(ref.current?.file!==selected)ref.current={file:selected,id:crypto.randomUUID()};await supportApi.upload(ticket.id,ref.current.id,selected);setSelected(null);ref.current=null;await reload()}catch(e){setError(e instanceof Error?e.message:'첨부 저장 실패')}finally{guard.current=false;setBusy(false)}}
 return <section className="panel support-attachments"><h2>비공개 첨부 · {ticket.attachments.length}/5</h2><p className="item-meta">작성자와 관리자만 다운로드합니다. 주민번호·비밀번호 등은 가리고 올려주세요.</p>{ticket.attachments.map((a,i)=><button className="btn secondary" key={a.id} onClick={()=>void supportApi.download(ticket.id,a.id,admin).catch(e=>setError(e.message))}>첨부 {i+1} 다운로드 · {Math.ceil(a.size/1024)}KB</button>)}{!ticket.attachments.length&&<p>첨부한 파일이 없습니다.</p>}{!admin&&enabled&&ticket.attachments.length<5&&!['CLOSED','RESOLVED'].includes(ticket.status)&&<><label className="field"><span>JPG·PNG·WebP, 파일당 5MiB 이하</span><input type="file" className="input" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>setSelected(e.target.files?.[0]??null)}/></label><button className="btn secondary" disabled={!selected||busy} onClick={()=>void upload()}>{busy?'첨부 중…':error?'같은 파일 다시 첨부':'첨부 저장'}</button></>}{!admin&&!enabled&&<small>현재 첨부 접수는 준비 중입니다. 본문과 공개 근거 링크로 먼저 알려주세요.</small>}{error&&<p className="form-alert" role="alert">{error}</p>}</section>
}
