/* Executes the actual LibraryProvider handlers with explicit hooks/API/storage doubles.
   Effects are registered, not a React runtime; mutations consult the real AuthSession snapshot. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
const root=path.resolve(__dirname,'../..'),ts=require('../v4/load_ts.cjs')();
function setup(){
 const cache=new Map(),effects=[];let frame;
 class Storage{m=new Map();get length(){return this.m.size}key(i){return [...this.m.keys()][i]??null}getItem(k){return this.m.get(k)??null}setItem(k,v){this.m.set(k,v)}removeItem(k){this.m.delete(k)}}
 const storage=new Storage(),jsx=(type,props)=>({type,props});
 const hooks={createContext:value=>({value,Provider:'Provider'}),useContext:c=>c.value,useState:init=>{const f=frame,i=f.i++;if(!(i in f.slots))f.slots[i]=typeof init==='function'?init():init;return[f.slots[i],v=>f.slots[i]=typeof v==='function'?v(f.slots[i]):v]},useRef:init=>{const f=frame,i=f.i++;return f.slots[i]??(f.slots[i]={current:init})},useMemo:(fn,deps)=>{const f=frame,i=f.i++;const old=f.slots[i];if(!old||deps.some((x,n)=>x!==old.deps[n]))f.slots[i]={deps,value:fn()};return f.slots[i].value},useCallback:(fn,deps)=>hooks.useMemo(()=>fn,deps),useEffect:fn=>effects.push(fn),useLayoutEffect:fn=>effects.push(fn)};
 const calls={memberSaves:0,resolves:0,index:0},config={user:{id:41,displayName:'[TEST] A',permissions:['FAN']},failure:null,gate:null};
 const authApi={me:async()=>{if(config.failure)throw config.failure;return config.user},logout:async()=>{config.failure={status:401}}};
 const libraryApi={index:async()=>{calls.index++;return[]},save:async()=>{calls.memberSaves++;if(config.gate)await config.gate;return{created:true,item:{id:'saved'}}},resolve:async targets=>{calls.resolves++;if(config.gate)await config.gate;return targets.map(t=>({target:t,available:true,current:{memory:{title:'[TEST] 부스',eventName:'[TEST] 행사',participantName:'[TEST] 부스',summary:'가상 소개',tags:[]},occurrences:[{startDate:'2026-09-01',endDate:'2026-10-31'}],locations:[]},image:null}))}};
 function load(rel){const f=path.resolve(root,rel);if(cache.has(f))return cache.get(f).exports;const m={exports:{}};cache.set(f,m);const code=ts.transpileModule(fs.readFileSync(f,'utf8').replace(/\bimport\.meta\.env\b/g,'({})'),{fileName:f.replace(/\.mjs$/,'.js'),compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const req=name=>{if(name==='react')return hooks;if(name==='react/jsx-runtime')return{jsx,jsxs:jsx,Fragment:'Fragment'};if(name==='../api')return{authApi};if(name.endsWith('/api/client'))return{API_BASE_URL:'https://backend.test'};if(f.replace(/\\/g,'/').includes('/library/')&&name==='./api')return{libraryApi};const p=path.resolve(path.dirname(f),name);for(const suffix of ['', '.ts','.tsx','/index.ts'])if(fs.existsSync(p+suffix)&&fs.statSync(p+suffix).isFile())return load(p+suffix);throw Error('unmocked '+name)};
 vm.runInNewContext(code,{require:req,module:m,exports:m.exports,console,URL,URLSearchParams,Date,Intl,Error,window:{location:{host:'boothhana.test'},localStorage:storage,addEventListener(){},removeEventListener(){}},document:{visibilityState:'visible',addEventListener(){},removeEventListener(){}},setTimeout,clearTimeout},{filename:f});return m.exports}
 function runner(fn){const f={i:0,slots:[]};return()=>{frame=f;f.i=0;return fn({children:null})}}
 const {AuthSession}=load('frontend/src/app/AuthSession.ts'),session=new AuthSession(authApi.me,authApi.logout),ctx=load('frontend/src/app/auth-context.ts').AuthContext,lib=load('frontend/src/features/library/LibraryProvider.tsx');
 const render=runner(lib.LibraryProvider),bind=()=>{ctx.value={...session.read(),loading:session.read().status==='checking',getSnapshot:session.read,refresh:session.refresh,logout:session.logout,loginUrl:'/api/auth/login'};return render().props.value};
 return {storage,calls,config,session,bind,fresh:()=>{ctx.value={...session.read(),getSnapshot:session.read,refresh:session.refresh};return runner(lib.LibraryProvider)().props.value},effects};
}
const input={target:{type:'PARTICIPANT',eventId:10,id:20,participantId:20},day:'',hall:''};
test('successful member save then me503: stale handler cannot write member OR guest',async()=>{const x=setup();await x.session.refresh();const l=x.bind();await l.save(input);assert.equal(x.calls.memberSaves,1);x.config.failure={status:503};await x.session.refresh();await assert.rejects(l.save(input));assert.equal(x.storage.length,0);assert.equal(x.calls.memberSaves,1);const failed=x.fresh();assert.equal(failed.owner,'error');assert.equal(failed.guest.length,0);assert.equal(failed.index.length,0);await assert.rejects(failed.save(input));assert.equal(x.storage.length,0)});
test('only explicit anonymous identity permits device writes',async()=>{const x=setup();x.config.failure={status:401};await x.session.refresh();const l=x.bind();assert.equal(l.owner,'guest');await l.save(input);assert.equal(x.storage.length,1);assert.equal(x.calls.memberSaves,0)});
test('checking identity pauses guest save before any public request',async()=>{const x=setup(),l=x.bind();await assert.rejects(l.save(input));assert.equal(x.calls.resolves,0);assert.equal(x.storage.length,0)});
test('guest public lookup finishing after account change must not write local store',async()=>{const x=setup();x.config.failure={status:401};await x.session.refresh();const l=x.bind();let finish;x.config.gate=new Promise(r=>finish=r);const save=l.save(input);x.config.failure=null;await x.session.refresh();finish();await assert.rejects(save);assert.equal(x.storage.length,0)});
test('account change invalidates late member completion, without misreporting a saved result',async()=>{const x=setup();await x.session.refresh();const l=x.bind();let finish;x.config.gate=new Promise(r=>finish=r);const save=l.save(input);x.config.user={...x.config.user,id:42};await x.session.refresh();finish();await assert.rejects(save);assert.equal(x.calls.memberSaves,1);assert.equal(x.storage.length,0);assert.equal(x.fresh().owner,'member:42')});
test('recovered identity uses same member mode; failed identity is not implicit import',async()=>{const x=setup();await x.session.refresh();x.config.failure={status:503};await x.session.refresh();assert.equal(x.bind().owner,'error');x.config.failure=null;await x.session.refresh();const l=x.fresh();await l.save(input);assert.equal(l.owner,'member:41');assert.equal(x.calls.memberSaves,1);assert.equal(x.storage.length,0)});
