const test=require('node:test'),assert=require('node:assert/strict');
const {setup,nodes,text,defaultLibrary}=require('./support/views.cjs');
const find=(tree,predicate)=>nodes(tree).find(predicate);
test('invalid custom dates show a validation state, not zero published events',()=>{const x=setup({search:'period=custom&from=2026-10-04&to=2026-10-03',response:{items:[],total:0}}),tree=x.render();assert.ok(text(tree).includes('날짜 범위를 먼저 확인해 주세요'));assert.equal(text(find(tree,n=>n.props.className==='discovery-result-count')).includes('0'),false);assert.equal(text(tree).includes('조건에 맞는 공개 행사가 없어요'),false)});
test('invalid date inputs identify and describe the error',()=>{const x=setup({search:'period=custom&from=2026-10-04&to=2026-10-03'}),tree=x.render();const inputs=nodes(tree).filter(n=>n.type==='input'&&n.props.type==='date');assert.equal(inputs.length,2);for(const n of inputs){assert.equal(n.props['aria-invalid'],true);assert.equal(n.props['aria-describedby'],'discovery-date-error')}});
test('a period-only filter has a visible individually removable condition',()=>{const x=setup({search:'period=weekend&region=&q='}),tree=x.render();const chip=find(tree,n=>n.type==='button'&&text(n).includes('기간 해제'));assert.ok(chip);assert.ok(text(chip).includes('이번 주말'));chip.props.onClick();assert.equal(x.params.get('period'),'all')});
test('removing a period preserves region and search text',()=>{const x=setup({search:'period=custom&from=2026-10-03&to=2026-10-04&region=GYEONGGI&q=문구&page=8'});find(x.render(),n=>n.type==='button'&&text(n).includes('기간 해제')).props.onClick();assert.equal(x.params.get('q'),'문구');assert.equal(x.params.get('region'),'GYEONGGI');assert.equal(x.params.has('from'),false);assert.equal(x.params.has('page'),false)});
test('out-of-range page recovery keeps all search filters',()=>{const x=setup({search:'period=weekend&q=엽서&region=SEOUL&page=30',response:{items:[],total:30}});const tree=x.render();const button=find(tree,n=>n.type==='button'&&text(n)==='같은 조건의 첫 페이지로');assert.ok(button);button.props.onClick();assert.equal(x.params.has('page'),false);assert.equal(x.params.get('period'),'weekend');assert.equal(x.params.get('q'),'엽서');assert.equal(x.params.get('region'),'SEOUL')});
test('out-of-range page does not present a nonsensical 31 / 2 pager',()=>{const x=setup({search:'page=30',response:{items:[],total:30}});assert.equal(nodes(x.render()).some(n=>n.props.className==='discovery-pagination'),false)});
test('empty booth reset clears saved-only, search and hall while preserving day',()=>{const x=setup({kind:'catalog',search:'section=booths&day=2026-10-03&hall=B홀&q=missing&my=saved'});const tree=x.render();const reset=find(tree,n=>n.type==='button'&&['모든 부스 조건 해제','검색 초기화'].includes(text(n)));assert.ok(reset);reset.props.onClick();for(const key of ['my','q','hall','focus','product','booth'])assert.equal(x.params.has(key),false,key);assert.equal(x.params.get('day'),'2026-10-03')});
for(const [label,library] of [['loading',{...defaultLibrary,loading:true}],['error',{...defaultLibrary,error:'일시 오류'}],['identity checking',{...defaultLibrary,owner:'loading',loading:false}],['missing provider',null]])test(`saved-only ${label} is not shown as an empty booth list`,()=>{const x=setup({kind:'catalog',search:'section=booths&my=saved&day=2026-10-03',library}),tree=x.render();const list=find(tree,n=>n.props['aria-label']==='참가 부스 목록');assert.equal(list,undefined);assert.ok(text(tree).includes('기록을 확인하기 전에는 부스가 없다고 판단하지 않습니다.'))});
test('ordinary public booths remain usable when private memory lookup fails',()=>{const x=setup({kind:'catalog',search:'day=2026-10-03&section=booths',library:{...defaultLibrary,error:'network'}}),tree=x.render();assert.equal(Boolean(find(tree,n=>n.props['aria-label']==='참가 부스 목록').props.hidden),false)});
test('unverified personal map is not rendered with previous account highlights',()=>{const x=setup({kind:'catalog',search:'section=map&my=saved&view=map',maps:{plans:[{id:'synthetic-map',state:'READY'}],managedAssetIds:[]},library:{...defaultLibrary,loading:true,index:[{target:{eventId:1,participantId:20},visitedDays:[]}]}}),tree=x.render();assert.equal(find(tree,n=>typeof n.type==='function'&&n.props.savedParticipantIds),undefined);assert.equal(find(tree,n=>n.props.className==='visit-map-section'),undefined);assert.ok(text(tree).includes('기록을 확인하기 전에는 부스가 없다고 판단하지 않습니다.'))});
for(const category of ['subculture','exhibitions','festivals'])test(`${category} mobile navigation exposes library and account destinations`,()=>{
 const x=setup({kind:'layout',search:'category='+category}),tree=x.render();
 const {SubcultureMobileNav}=x.h.load('frontend/src/features/subculture/SubcultureChrome.tsx');
 const nested=find(tree,n=>n.type===SubcultureMobileNav);
 // This source harness does not expand function components automatically.
 const nav=nested?x.h.render(nested.type,nested.props):find(tree,n=>n.props.className==='public-mobile-nav');
 assert.ok(nav);for(const route of ['/library','/account'])assert.ok(nodes(nav).some(n=>n.props.to===route));
 assert.equal(nodes(nav).some(n=>n.props.href==='/offline/index.html'),false);
 assert.equal(Boolean(nested),category==='subculture');
 if(nested){assert.equal(nav.props['aria-label'],'주요 메뉴');assert.ok(nodes(nav).some(n=>n.props.to==='/subculture/search'))}
});
