const test=require('node:test'),assert=require('node:assert/strict');
const {runtime,nodes,text}=require('../v22/support/runtime.cjs');
const {setup}=require('./support/library.cjs');
const find=(tree,p)=>nodes(tree).find(p);
const tick=async()=>{for(let i=0;i<4;i++)await new Promise(setImmediate)};
function panel({packs=[],loading=false,owner='guest',libraryOwner=owner}={}){const downloads=[],auth={getSnapshot:()=>({status:'anonymous'})};const h=runtime({resolve(name){
 if(name==='react-router')return {Link:'a'};
 if(name.endsWith('/auth-context'))return {AuthContext:{value:auth}};
 if(name.endsWith('/api/client'))return {API_BASE_URL:'https://example.invalid'};
 if(name.endsWith('/LibraryProvider'))return {useLibrary:()=>({owner:libraryOwner,loading,error:'',index:[{target:{eventId:1,type:'PRODUCT',id:9},note:'private note'},{target:{eventId:2,type:'PRODUCT',id:10}},{target:{eventId:1,type:'EVENT',id:1}}]})};
 if(name.endsWith('/offlineModule'))return {loadOfflineModule:async()=>({syncOwner:async()=>{},listPacks:async()=>packs,downloadEvent:async args=>{downloads.push(args);return {bytes:0,missing:[]}}})};
 if(name.endsWith('/OfflinePrivacyGuard'))return {offlineOwner:()=>owner};
 }});const button=h.load('frontend/src/features/offline/OfflineDownloadPanel.tsx').OfflineEventButton;return {h,downloads,render:()=>h.render(button,{eventId:1,day:'2026-10-03'})}}
test('library download requires an explicit click and sends only current-event public selection',async()=>{const x=panel();x.render();x.h.flushEffects();await tick();let tree=x.render();assert.equal(x.downloads.length,0);assert.ok(text(tree).includes('이 기기에 7일간 저장합니다.'));const button=find(tree,n=>n.type==='button');assert.equal(button.props.disabled,false);button.props.onClick();await tick();assert.equal(x.downloads.length,1);assert.deepEqual(JSON.parse(JSON.stringify(x.downloads[0].selection)),[{type:'PRODUCT',id:9}]);assert.equal(x.downloads[0].day,'2026-10-03');assert.equal(JSON.stringify(x.downloads).includes('private note'),false);x.h.unmount()});
for(const config of [{loading:true},{owner:null},{libraryOwner:'member:2'}])test(`offline save blocks unresolved identity or selection ${JSON.stringify(config)}`,async()=>{const x=panel(config);x.render();x.h.flushEffects();await tick();const button=find(x.render(),n=>n.type==='button');assert.equal(button.props.disabled,true);await button.props.onClick();assert.equal(x.downloads.length,0);x.h.unmount()});
test('saved event opens the library reader with the event selected',async()=>{const x=panel({packs:[{id:1}]});x.render();x.h.flushEffects();await tick();assert.ok(find(x.render(),n=>n.props.to==='/library?offline=1&offlineEvent=1'));x.h.unmount()});
test('library offline tab embeds the selected event without private memory editor',()=>{const tree=setup({search:'offline=1&offlineEvent=7'}).render();assert.ok(find(tree,n=>n.type==='iframe'&&n.props.src==='/offline/index.html?embedded=1#7'));assert.equal(nodes(tree).some(n=>n.type==='input'&&n.props.type==='search'),false)});
test('library explicit search submits without waiting for debounce',()=>{const x=setup();let tree=x.render();find(tree,n=>n.type==='input'&&n.props.type==='search').props.onChange({target:{value:'엽서'}});tree=x.render();assert.equal(new URLSearchParams(x.calls[1].deps[2]).get('q'),'');find(tree,n=>n.type==='form').props.onSubmit({preventDefault(){}});x.render();assert.equal(new URLSearchParams(x.calls[1].deps[2]).get('q'),'엽서')});
test('library clear button removes search only, preserving event and type',()=>{const x=setup({search:'q=엽서&event=7&type=PRODUCT&group=event'}),tree=x.render();const clear=find(tree,n=>n.type==='button'&&text(n)==='검색어 지우기');assert.ok(clear);clear.props.onClick();x.render();assert.equal(x.params.has('q'),false);assert.equal(x.params.get('event'),'7');assert.equal(x.params.get('type'),'PRODUCT');assert.equal(new URLSearchParams(x.calls[1].deps[2]).get('q'),'')});
test('selected event stays legible before its group label is loaded',()=>{const x=setup({search:'event=7'}),tree=x.render();assert.ok(find(tree,n=>n.type==='option'&&String(n.props.value)==='7'&&text(n).includes('선택한 행사')))});
test('guest list does not promise permanent account retention',()=>{const tree=setup({owner:'guest'}).render();assert.ok(text(tree).includes('기기 임시 기록 · 저장일로부터 90일'));assert.equal(text(tree).includes('행사가 끝나도 계정 저장 기록은 유지돼요.'),false)});
