import type { Occurrence, OperationStatus } from '../collection/api'
import type { Product } from '../catalog/api'
import { scopes, saleStates } from '../catalog/Shared'
import { operationLabels } from './eventStatus'
export function OccurrenceFields({value,change,disabled=false}:{value:Occurrence[];change:(v:Occurrence[])=>void;disabled?:boolean}) {
  const update=(i:number,p:Partial<Occurrence>)=>change(value.map((v,n)=>i===n?{...v,...p}:v))
  return <fieldset className="visit-form-fields" disabled={disabled}><legend>실제 운영일</legend><p>중간에 쉬는 날이 있으면 기간을 나눠 추가하세요.</p>
    {value.map((o,i)=><div className="visit-occurrence-row" key={i}><label className="field"><span>시작일</span><input className="input" type="date" value={o.startDate} onChange={e=>update(i,{startDate:e.target.value,endDate:o.endDate||e.target.value})}/></label><label className="field"><span>종료일</span><input className="input" type="date" value={o.endDate} min={o.startDate} onChange={e=>update(i,{endDate:e.target.value})}/></label><label className="field"><span>시작 시간 · 미정은 비움</span><input className="input" type="time" value={o.startTime||''} onChange={e=>update(i,{startTime:e.target.value||null})}/></label><label className="field"><span>종료 시간</span><input className="input" type="time" value={o.endTime||''} onChange={e=>update(i,{endTime:e.target.value||null})}/></label><button type="button" className="btn secondary" onClick={()=>change(value.filter((_,n)=>n!==i))}>기간 제거</button></div>)}
    <button type="button" className="btn secondary" onClick={()=>change([...value,{startDate:'',endDate:'',startTime:null,endTime:null}])}>운영 기간 추가</button></fieldset>
}
export function OperationFields({value,change,disabled=false}:{value:OperationStatus;change:(v:OperationStatus)=>void;disabled?:boolean}) {
  return <fieldset disabled={disabled} className="visit-form-fields"><legend>개최 상태·중요 안내</legend><p>날짜만 보고 개최·취소를 추정하지 마세요. 확인한 원문과 확인일이 필요합니다.</p>
    <div className="form-grid"><label className="field"><span>개최 상태</span><select className="select" value={value.state} onChange={e=>change({...value,state:e.target.value as OperationStatus['state']})}>{Object.entries(operationLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
    <label className="field"><span>확인일</span><input className="input" type="date" value={value.checkedOn||''} onChange={e=>change({...value,checkedOn:e.target.value||null})}/></label><label className="field full"><span>확인 원문 주소</span><input className="input" type="url" value={value.sourceUrl||''} onChange={e=>change({...value,sourceUrl:e.target.value||null})}/></label><label className="field full"><span>방문자에게 표시할 안내</span><textarea className="textarea" value={value.note||''} maxLength={500} onChange={e=>change({...value,note:e.target.value||null})}/></label></div></fieldset>
}
export function DateListFields({value,change,disabled=false,label='적용 날짜'}:{value:string[];change:(v:string[])=>void;disabled?:boolean;label?:string}) {
  return <fieldset className="visit-form-fields" disabled={disabled}><legend>{label}</legend><p>실제로 적용되는 날짜만 추가하세요. 미확인은 비워 둡니다.</p>{value.map((d,i)=><div className="row-actions" key={i}><input className="input" type="date" aria-label={`${label} ${i+1}`} value={d} onChange={e=>change(value.map((v,n)=>n===i?e.target.value:v))}/><button className="btn secondary" type="button" onClick={()=>change(value.filter((_,n)=>n!==i))}>날짜 제거</button></div>)}<button className="btn secondary" type="button" onClick={()=>change([...value,''])}>날짜 추가</button></fieldset>
}
export function ProductFields({value,change,disabled=false}:{value:Product[];change:(v:Product[])=>void;disabled?:boolean}) {
  const edit=(index:number,patch:Partial<Product>)=>change(value.map((v,i)=>index===i?{...v,...patch}:v))
  return <fieldset className="visit-form-fields" disabled={disabled}><legend>확보한 개별 상품 · {value.length}개</legend><p>기존 출처·상품 ID는 유지됩니다. 미확인은 빈 값 또는 ‘미확인’을 선택하세요.</p>
    {value.map((p,i)=><details key={i} className="visit-product-editor"><summary>{p.name} · {saleStates[p.saleState]||'미확인'}</summary><div className="form-grid"><label className="field"><span>상품명</span><input className="input" value={p.name} maxLength={255} onChange={e=>edit(i,{name:e.target.value})}/></label><label className="field"><span>판매 상태</span><select className="select" value={p.saleState} onChange={e=>edit(i,{saleState:e.target.value})}>{Object.entries(saleStates).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field full"><span>행사와의 관련성</span><select className="select" value={p.evidenceScope} onChange={e=>edit(i,{evidenceScope:e.target.value as Product['evidenceScope']})}>{Object.entries(scopes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field full"><span>짧은 설명</span><textarea className="textarea" value={p.summary} maxLength={1000} onChange={e=>edit(i,{summary:e.target.value})}/></label>
      <label className="check-field"><input type="checkbox" checked={p.price!==null} onChange={e=>edit(i,{price:e.target.checked?{amount:'',currency:'KRW',checkedOn:'',note:null}:null})}/>가격을 확인했어요</label>
      {p.price&&<><label className="field"><span>표시 가격</span><input className="input" type="number" min="0" step="0.01" value={p.price.amount} onChange={e=>edit(i,{price:{...p.price!,amount:e.target.value}})}/></label><label className="field"><span>통화 코드</span><input className="input" value={p.price.currency} maxLength={3} onChange={e=>edit(i,{price:{...p.price!,currency:e.target.value.toUpperCase()}})}/></label><label className="field"><span>가격 확인일</span><input className="input" type="date" value={p.price.checkedOn} onChange={e=>edit(i,{price:{...p.price!,checkedOn:e.target.value}})}/></label><label className="field full"><span>가격 조건 · 옵션/배송비</span><input className="input" value={p.price.note||''} onChange={e=>edit(i,{price:{...p.price!,note:e.target.value||null}})}/></label></>}
      <label className="field full"><span>방문자 주의사항 · 한 줄에 하나</span><textarea className="textarea" value={p.warnings.join('\n')} onChange={e=>edit(i,{warnings:e.target.value.split('\n').filter(Boolean)})}/></label></div></details>)}
  </fieldset>
}
