import {useState,useRef} from 'react'
import {Link} from 'react-router'
import {api} from '../../api/client'
import {useRemote} from '../../app/useRemote'
import {SafeLink} from './Shared'
import {seoulToday} from '../discovery/browse'
import type {EventDetail} from './api'
import {useDirty} from '../visit/UnsavedChanges'
import '../discovery/explore.css'
interface Observation {id:string;eventRevision:number;state:string;observedAt:string;sources:string[];changes:Record<string,{before:unknown;after:unknown;evidence?:string}>;reviewNote:string}
interface Result {checks:{status:string;checked_at:string;next_check_at:string;failures:number;details_json:{fieldStates?:Record<string,string>;fieldEvidence?:Record<string,string>}}[];items:Observation[];places:{neighborhood:string;latitude:number|null;longitude:number|null;source_url:string;checked_on:string}[]}
const labels:Record<string,string>={venueName:'장소',address:'주소',admission:'입장 조건',occurrences:'날짜·시간',operationStatus:'개최 상태',visitorGuide:'예매·프로그램',districts:'개최 구',CONFIRMED:'확인 완료',SOURCE_UNPUBLISHED:'원문 미공개',ACCESS_FAILED:'접근 실패',EXTRACTION_FAILED:'추출 실패',CONFLICT_REVIEW:'변경 검토',PENDING:'검토 대기',APPLIED:'수정본에 반영',REJECTED:'제외'}
export function ObservationSummary(){
 const data=useRemote("features/catalog/ObservationWorkspace:ObservationSummary:data", ()=>api<{pending:{pending:number;oldest:string|null};checks:{status:string;count:number}[];todayReviews:{count:number;seconds:number};workload?:{eligible:number;due:number;near:number;near_checked:number};queue:{event_id:number;name:string;observed_at:string;observations:number}[]}>('/api/admin/subculture/v4/recheck-summary'),[])
 if(data.loading)return <p role="status">재확인 현황을 확인하고 있어요.</p>
 if(data.error)return <p role="alert">재확인 현황을 불러오지 못했어요. <button className="btn secondary" onClick={()=>void data.reload()}>다시 확인</button></p>
 const value=data.data;if(!value)return null
 return <section className="panel"><h2>재확인·정정 현황</h2><p>변경 검토 대기 {value.pending.pending}건{value.pending.oldest&&` · 가장 오래된 관측 ${new Date(value.pending.oldest).toLocaleString('ko-KR')}`}</p><p>{value.checks.map(c=>`${labels[c.status]} ${c.count}건`).join(' · ')||'재확인 실행 기록 없음'}</p><p>{value.workload&&`재확인 대상 ${value.workload.eligible}개 · 기한이 지난 작업 ${value.workload.due}개 · 7일 이내 행사 중 최근 24시간 원문 확인 ${value.workload.near_checked}/${value.workload.near}개`}</p><p>오늘 검토 {value.todayReviews.count}건 · 화면에서 기록된 검토 시간 {Math.round(value.todayReviews.seconds/60)}분</p><small>검토 시간에는 화면을 열어둔 시간이 포함됩니다. 실제 인력 부담은 별도 운영 기록과 함께 확인하세요.</small>{value.queue.length>0&&<details><summary>오래된 검토 대기 행사 (최대 20개)</summary><ul>{value.queue.map(q=><li key={q.event_id}><Link to={`/admin/subculture?event=${q.event_id}`}>{q.name}</Link> · {q.observations}건</li>)}</ul></details>}<button className="btn secondary" onClick={()=>void data.reload()}>현황 새로고침</button></section>
}
export function ObservationWorkspace({detail,saved}:{detail:EventDetail;saved:()=>void}){
 const base=`/api/admin/subculture/v4/events/${detail.id}`,data=useRemote("features/catalog/ObservationWorkspace:ObservationWorkspace:data", ()=>api<Result>(`${base}/observations`),[detail.id,detail.revision])
 return <section className="panel"><h3>공식 정보 재확인</h3><p>새 관측은 공개본을 바꾸지 않습니다. 변경값을 반영한 뒤 행사 검토와 공개본 갱신을 완료하세요.</p>{data.loading&&!data.data?<p role="status">확인 기록을 불러오고 있어요.</p>:data.error?<p role="alert">기록을 불러오지 못했어요. <button className="btn secondary" onClick={()=>void data.reload()}>다시 확인</button></p>:<>{data.data?.checks.map((c,i)=><div key={i}><p>{labels[c.status]} · 원문 확인 {new Date(c.checked_at).toLocaleString('ko-KR')} · 다음 확인 {new Date(c.next_check_at).toLocaleString('ko-KR')} · 연속 실패 {c.failures}</p>{Object.entries(c.details_json.fieldStates??{}).map(([field,status])=><p className="item-meta" key={field}>{labels[field]||field}: {labels[status]||status}</p>)}</div>)}{!data.data?.checks.length&&<p>아직 재확인 작업이 실행되지 않았습니다.</p>}{data.data?.items.map(o=><ObservationReview key={o.id} detail={detail} item={o} done={()=>{saved();void data.reload()}}/>)}<PlaceEditor key={detail.revision} detail={detail} place={data.data?.places[0]} saved={()=>void data.reload()}/></>}
 </section>
}
function ObservationReview({detail,item,done}:{detail:EventDetail;item:Observation;done:()=>void}){
 const [fields,setFields]=useState<string[]>([]),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),began=useRef(Date.now())
 const clean=useDirty(`observation-${item.id}`,{fields:[],note:''},item.state==='PENDING'?{fields,note}:{fields:[],note:''})
 const stale=detail.revision!==item.eventRevision
 const submit=async(reject:boolean)=>{if(busy)return;setBusy(true);setError('');try{await api(`/api/admin/subculture/v4/events/${detail.id}/observations/${item.id}/review`,{method:'POST',body:JSON.stringify({eventRevision:item.eventRevision,fields,note,reviewSeconds:Math.min(86400,Math.floor((Date.now()-began.current)/1000)),reject})});setFields([]);setNote('');clean();done()}catch(e){setError(e instanceof Error?e.message:'반영하지 못했습니다.')}finally{setBusy(false)}}
 return <article className="observation-item"><h4>{labels[item.state]} · {new Date(item.observedAt).toLocaleString('ko-KR')}</h4>{item.sources.map(s=><p key={s}><SafeLink url={s}>관측 원문 ↗</SafeLink></p>)}{Object.entries(item.changes).map(([key,value])=><div key={key}><label><input type="checkbox" disabled={busy||stale||item.state!=='PENDING'} checked={fields.includes(key)} onChange={e=>setFields(e.target.checked?[...fields,key]:fields.filter(f=>f!==key))}/>{labels[key]||key} 반영</label>{value.evidence&&<p className="item-meta">원문 근거: {value.evidence}</p>}<div className="observation-diff"><div><strong>기존</strong><pre>{JSON.stringify(value.before,null,2)}</pre></div><div><strong>새 관측</strong><pre>{JSON.stringify(value.after,null,2)}</pre></div></div></div>)}{item.state==='PENDING'?<>{stale&&<p>관측 이후 수정된 행사입니다. 변경값을 직접 검토하거나 새 관측을 기다리세요.</p>}<label className="field"><span>검토 근거</span><textarea className="textarea" value={note} disabled={busy} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><div className="row-actions"><button className="btn primary" disabled={busy||stale||!fields.length||!note.trim()} onClick={()=>void submit(false)}>선택값을 수정본에 반영</button><button className="btn secondary" disabled={busy||!note.trim()} onClick={()=>void submit(true)}>관측 제외</button></div></>:<p>{item.reviewNote}</p>}{error&&<p role="alert">{error}</p>}</article>
}
function PlaceEditor({detail,place,saved}:{detail:EventDetail;place?:Result['places'][number];saved:()=>void}){
 const [neighborhood,setNeighborhood]=useState(place?.neighborhood||'SEONGSU'),[latitude,setLatitude]=useState(place?.latitude?.toString()||''),[longitude,setLongitude]=useState(place?.longitude?.toString()||''),[source,setSource]=useState(place?.source_url||''),[checked,setChecked]=useState(place?.checked_on?.slice(0,10)||seoulToday()),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [baseline,setBaseline]=useState({neighborhood,latitude,longitude,source,checked}),current={neighborhood,latitude,longitude,source,checked}
 useDirty(`place-${detail.id}`,baseline,current)
 const sources=detail.event.sources.filter(s=>s.access==='ORIGINAL'&&['OFFICIAL','VENUE','ORGANIZER_SOCIAL'].includes(s.kind))
 const submit=async()=>{if(busy)return;setBusy(true);setMessage('');try{await api(`/api/admin/subculture/v4/events/${detail.id}/place`,{method:'PUT',body:JSON.stringify({eventRevision:detail.revision,neighborhood,address:detail.event.address,latitude:latitude?Number(latitude):null,longitude:longitude?Number(longitude):null,sourceUrl:source,checkedOn:checked})});setBaseline(current);setMessage('동네 위치를 저장했습니다. 공개 주소가 변경되면 연결이 자동으로 숨겨집니다.');saved()}catch(e){setMessage(e instanceof Error?e.message:'저장 실패')}finally{setBusy(false)}}
 return <details><summary>동네·지도 위치 확인</summary><p>공식 주소의 동네를 확인해 연결하세요. 좌표는 확인한 경우에만 입력합니다.</p><fieldset disabled={busy}><div className="form-grid"><label className="field"><span>동네</span><select className="select" value={neighborhood} onChange={e=>setNeighborhood(e.target.value)}><option value="SEONGSU">성수·서울숲</option><option value="YEONNAM">연남</option></select></label><p>{detail.event.address||'공식 주소가 필요합니다.'}</p><label className="field"><span>위도 (선택)</span><input className="input" type="number" step="any" value={latitude} onChange={e=>setLatitude(e.target.value)}/></label><label className="field"><span>경도 (선택)</span><input className="input" type="number" step="any" value={longitude} onChange={e=>setLongitude(e.target.value)}/></label><label className="field"><span>공식 근거</span><select className="select" value={source} onChange={e=>setSource(e.target.value)}><option value="">출처 선택</option>{sources.map(s=><option key={s.url} value={s.url}>{s.url}</option>)}</select></label><label className="field"><span>확인일</span><input className="input" type="date" value={checked} max={seoulToday()} onChange={e=>setChecked(e.target.value)}/></label></div><button className="btn primary" disabled={!source||!detail.event.address} onClick={()=>void submit()}>확인한 동네 저장</button></fieldset>{message&&<p role="status">{message}</p>}</details>
}
