/* Source-generated static preview. No React DOM, API calls or live user information. */
const fs=require('node:fs'),path=require('node:path');
const {harness,toHtml,root}=require('../v10/source_harness.cjs');
const out=path.join(root,'preview/v12');fs.mkdirSync(out,{recursive:true});
const css=['styles/tokens.css','styles/global.css','features/discovery/discovery.css','styles/polish.css','features/support/support.css'].map(f=>fs.readFileSync(path.join(root,'frontend/src',f),'utf8')).join('\n');
const ticket={id:'11111111-2222-3333-4444-555555555555',number:'BH-11111111',kind:'REPORT',category:'PARTICIPATION_LOCATION',title:'[예시] 부스 위치 변경을 확인해 주세요',status:'IN_PROGRESS',revision:2,createdAt:'2026-09-17T00:00:00Z',updatedAt:'2026-09-17T01:00:00Z',resolution:null,target:{namespace:'CATALOG',type:'PARTICIPANT',eventId:10,id:20,day:'2026-10-11',hall:'1관'},receivedSnapshot:{label:'[예시] 달토끼공방 · B1',route:'/discover/10?booth=20',data:{booth:'B1'}},receivedFingerprint:'test-only',clientContext:{viewedVersion:'화면 확인용 예시 버전'},attachments:[],messages:[{id:'1',author:'USER',internal:false,body:'[가상 문의] 둘째 날 참가 위치가 공식 공지와 다르게 보여요. 확인을 부탁드립니다.',evidence:[],createdAt:'2026-09-17T00:00:00Z'},{id:'2',author:'ADMIN',internal:false,body:'[가상 답변] 알려주셔서 감사합니다. 행사 공지와 참가 정보를 비교해 확인하고 있습니다. 결과는 이 접수 내역에서 안내하겠습니다.',evidence:[],createdAt:'2026-09-17T01:00:00Z'}],actions:[{action:'START',actorId:2,createdAt:'2026-09-17T01:00:00Z',details:{note:'[가상 내부 이력] 공식 공지 확인 필요'}}],requesterId:1,assignedTo:2,eventRevision:3,currentTarget:{visible:true,label:'[예시] 달토끼공방',route:'/discover/10?booth=20',fingerprint:'test-only',snapshot:{booth:'B1'}},verifiedManagers:[]};
function expand(app,n){if(n==null||typeof n!=='object')return n;if(Array.isArray(n))return n.map(x=>expand(app,x));if(typeof n.type==='function')return expand(app,app.render(n.type,n.props,true));let children=expand(app,n.props.children);if(n.type==='select')children=[children].flat(Infinity).map(c=>c?.type==='option'?{...c,props:{...c.props,selected:String(c.props.value)===String(n.props.value)}}:c);return {...n,props:{...n.props,children}};}
function save(name,app,component,props={}){let content=toHtml(expand(app,app.render(component,props,true)));const links=['center','inquiry','my-report','admin-report','admin-inquiries','guest'].map(x=>`<a href="${x}.html">${x}</a>`).join(' · ');fs.writeFileSync(path.join(out,name+'.html'),`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>부스하나 v12 화면 시안</title><style>${css}\nbody{background:#f5f7fa}.preview-note{padding:14px;background:#fff3cc;font-size:14px;line-height:1.6}.preview-note a{display:inline-block;min-height:30px}.preview-shell{max-width:1180px;margin:auto;padding:0 18px 50px}pre{max-width:100%}input,select,textarea{max-width:100%}</style><body><div class="preview-note">가상 데이터·정적 시안입니다. 실제 접수·답변·계정·관리자 처리·파일 업로드가 작동하는 화면이 아닙니다.<nav>${links}</nav></div><main class="preview-shell">${content}</main><script>document.addEventListener('submit',e=>e.preventDefault());document.querySelectorAll('a[href^="/"]').forEach(a=>a.addEventListener('click',e=>e.preventDefault()));</script></body></html>`);}
let app=harness({auth:{user:{id:1,displayName:'예시 사용자',permissions:['FAN','CREATOR']},loading:false},remote:{loading:false,error:null,data:{items:[ticket],page:0,size:20,total:1}}});save('center',app,app.load('frontend/src/features/support/SupportPages.tsx').SupportHome);
app=harness({location:{pathname:'/support/new',search:''},auth:{user:{id:1,permissions:['FAN','CREATOR']},loading:false},remote:{loading:false,error:null,data:null}});save('inquiry',app,app.load('frontend/src/features/support/SupportPages.tsx').SupportNew);
app=harness({auth:{user:{id:1},loading:false},params:{id:ticket.id},remote:{loading:false,error:null,data:ticket}});save('my-report',app,app.load('frontend/src/features/support/SupportPages.tsx').SupportDetail);
app=harness({params:{id:ticket.id},remote:{loading:false,error:null,data:{...ticket,messages:[...ticket.messages,{id:'3',author:'ADMIN',internal:true,body:'[가상 내부 메모] 이 문장은 작성자 화면에 전달되지 않습니다.',evidence:[],createdAt:'2026-09-17T02:00:00Z'}]}}});save('admin-report',app,app.load('frontend/src/features/support/AdminSupportPages.tsx').AdminSupportDetail);
app=harness({remote:{loading:false,error:null,data:{items:[{...ticket,kind:'INQUIRY',category:'ACCOUNT',title:'[예시] 로그인에 문제가 있어요'}],total:1,page:0,size:20}}});save('admin-inquiries',app,app.load('frontend/src/features/support/AdminSupportPages.tsx').AdminSupportList,{kind:'INQUIRY'});
app=harness({remote:{loading:false,error:null,data:{guestEnabled:true}}});save('guest',app,app.load('frontend/src/features/support/GuestSupportPage.tsx').GuestSupportPage);
console.log('Rendered 6 source-based STATIC v12 pages. Not React/API execution.');
