/* Actual TypeScript functions/components in explicit hook harness. NOT browser/router E2E. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {harness,nodes,toHtml,root}=require('../v10/source_harness.cjs');let checks=0;
const check=(b,m)=>{checks++;assert.ok(b,m)};const app=harness();const rules=app.load('frontend/src/features/support/rules.ts');
const target={namespace:'CATALOG',type:'FLOORPLAN',eventId:10,id:null,planId:'a10b2c3d-1111-2222-3333-444444444444',areaId:'B1',day:'2026-10-10',hall:'1관'};
const url=rules.supportPath('REPORT',target,'2026-09-17T00:00:00Z');check(url.startsWith('/support/new?kind=REPORT'));const parsed=rules.readTarget(new URL('https://test.invalid'+url).searchParams);check(parsed.namespace==='CATALOG'&&parsed.areaId==='B1'&&parsed.day==='2026-10-10');
for(const v of [null,{}, {...target,namespace:'PRIVATE'}, {...target,eventId:0}, {...target,planId:'abc'}, {...target,hall:'x'.repeat(101)}, {...target,id:-1,type:'PRODUCT'}]){check(rules.readTarget(new URLSearchParams({target:JSON.stringify(v)}))===null,'bad target rejected');}
check(rules.parseKind('SQL')==='INQUIRY');check(rules.evidenceLines('https://example.test/a\n\nhttps://example.test/b').length===2);for(const s of ['javascript:alert(1)','https://user:secret@host.test','/relative']){let bad=false;try{rules.evidenceLines(s)}catch{bad=true}check(bad,'bad evidence');}
let keys=new Set();for(let i=0;i<100;i++){const key=rules.secureGuestKey();assert.match(key,/^[\w-]{43}$/);keys.add(key)}check(keys.size===100,'secure key sample unique, not proof of impossibility');check(rules.validGuest({ticketId:'11111111-2222-3333-4444-555555555555',accessKey:[...keys][0]}));check(!rules.validGuest({ticketId:'BH-1234',accessKey:'email@example.com'}));
const link=app.load('frontend/src/features/support/ReportLink.tsx').ReportLink;let tree=app.render(link,{target,label:'위치 오류 신고'},true);check(toHtml(tree).includes('위치 오류 신고'));check(tree.props.to.includes('FLOORPLAN'));check(tree.props.state.supportFrom.startsWith('/discover'));check(!tree.props.to.includes('body='),'no private text in URL');
const ticket={id:'11111111-2222-3333-4444-555555555555',number:'BH-11111111',kind:'REPORT',category:'OTHER',title:'[TEST] 위치를 확인해 주세요',status:'OPEN',revision:0,createdAt:'2026-09-17T00:00:00Z',updatedAt:'2026-09-17T00:00:00Z',resolution:null,target,receivedSnapshot:{label:'[TEST] 가상 행사 B1',route:'/discover/10',data:{}},receivedFingerprint:'hash',clientContext:{viewedVersion:'v1'},attachments:[],messages:[{id:'m1',author:'USER',internal:false,body:'[TEST] 지도 위치가 달라요.',evidence:['https://example.test/evidence'],createdAt:'2026-09-17T00:00:00Z'}]};
const views=app.load('frontend/src/features/support/TicketViews.tsx');tree=app.render(views.TicketHeader,{ticket},true);check(toHtml(tree).includes(ticket.title)&&toHtml(tree).includes('접수'));
tree=app.render(views.MessageThread,{ticket},true);check(toHtml(tree).includes('작성자')&&!toHtml(tree).includes('내부 메모'));
let privateTicket={...ticket,messages:[...ticket.messages,{id:'m2',author:'ADMIN',internal:true,body:'[TEST] 비공개 메모',evidence:[],createdAt:'2026-09-17T00:00:00Z'}]};tree=app.render(views.MessageThread,{ticket:privateTicket},true);check(toHtml(tree).includes('관리자 내부 메모'),'visible admin distinction; server filters user payload');
tree=app.render(views.ReplyForm,{ticket,admin:false,onSend:async()=>{}},true);check(!toHtml(tree).includes('내부 메모로 저장'),'user cannot select internal');tree=app.render(views.ReplyForm,{ticket,admin:true,onSend:async()=>{}},true);check(toHtml(tree).includes('사용자에게 보이지 않음'));tree=app.render(views.ReplyForm,{ticket:{...ticket,status:'CLOSED'},onSend:async()=>{}},true);check(!nodes(tree).some(n=>n.type==='form'),'closed input removed');
tree=app.render(views.Attachments,{ticket,enabled:false,reload:async()=>{}},true);check(toHtml(tree).includes('첨부 접수는 준비 중'));check(!nodes(tree).some(n=>n.type==='input'&&n.props.type==='file'));tree=app.render(views.Attachments,{ticket,enabled:true,reload:async()=>{}},true);check(nodes(tree).some(n=>n.type==='input'&&n.props.accept==='image/jpeg,image/png,image/webp'));
const homeApp=harness({auth:{user:null,loading:false,loginUrl:'/login'},remote:{loading:false,data:null,error:null}});const home=homeApp.load('frontend/src/features/support/SupportPages.tsx');tree=homeApp.render(home.SupportHome,{},true);check(toHtml(tree).includes('고객센터'));check(toHtml(tree).includes('비회원'));check(!toHtml(tree).includes('이메일 발송 완료'));
const guestApp=harness({remote:{loading:false,error:null,data:{guestEnabled:false}}});tree=guestApp.render(guestApp.load('frontend/src/features/support/GuestSupportPage.tsx').GuestSupportPage,{},true);check(toHtml(tree).includes('준비하고'),'default disabled honest');
const apiCode=fs.readFileSync(path.join(root,'frontend/src/features/support/api.ts'),'utf8');check(apiCode.includes("guestRead:(access:GuestAccess)=>post<Ticket>"));check(apiCode.includes("credentials:'include',cache:'no-store',redirect:'error'"));check(!apiCode.includes('R2_PUBLIC_URL'));
const guestCode=fs.readFileSync(path.join(root,'frontend/src/features/support/GuestSupportPage.tsx'),'utf8');check(!guestCode.includes('localStorage.set'));check(!guestCode.includes('sessionStorage.set'));check(guestCode.includes('30일'));check(guestCode.includes('비밀 조회키'));check(guestCode.includes('접수 ID·조회키 파일 저장'));
const router=fs.readFileSync(path.join(root,'frontend/src/app/router.tsx'),'utf8');for(const r of ['support/new','support/guest','support/tickets/:id','reports','inquiries','ownership','managed-exhibitors'])check(router.includes("path: '"+r+"'"),'route '+r);
const claims=fs.readFileSync(path.join(root,'frontend/src/features/support/AdminSupportPages.tsx'),'utf8');check(claims.includes('공동 부스·행사·예약·POS 편집권은 부여하지 않습니다'));check(claims.includes('overrides:{}'),'report closure does not blanket overwrite a whole catalogue');check(claims.includes('현재 공개 변경 확인 후 완료'));check(claims.includes('해당 행사에서 검토 완료된 정보가 함께 공개됩니다'));
const login=fs.readFileSync(path.join(root,'frontend/src/app/useAuth.ts'),'utf8');check(login.includes('encodeURIComponent(path)'));check(!login.includes('body'));
console.log(`PASS v12 ${checks} actual TS/UI+source-contract assertions (mock hooks, no React DOM/API)`);
