"""Generate deployment-local copies of the one reviewed taxonomy. Run --check in CI."""
from pathlib import Path
import json
import sys

ROOT=Path(__file__).resolve().parents[1]
raw=(ROOT/'taxonomy/catalog.json').read_text(encoding='utf-8')
data=json.loads(raw)
fields=data['fields']
all_types=[t['code'] for f in fields for t in f['types']]
assert len(all_types)==len(set(all_types)), 'Duplicate event type'
for field in fields:
    types={t['code'] for t in field['types']}
    assert not field.get('relatedTypes'), 'Fields must not share event types'
    for event_type in field['types']:
        if 'aliasOf' in event_type:
            assert event_type['aliasOf'] in types, 'Alias must belong to the same field'
            assert not next(t for t in field['types'] if t['code']==event_type['aliasOf']).get('aliasOf'), 'Aliases must resolve directly'
    for group in ('formats','topics'):
        codes=[o['code'] for o in field[group]]
        assert len(codes)==len(set(codes)), 'Duplicate option'
        for option in field[group]:
            assert set(option['types'])<=types, 'Cross-field type'
            assert set(option['works'])<=set(option['subjects']), 'Work aliases must remain backwards compatible'

def java_list(values):return 'List.of('+','.join(values)+')'
def java_strings(values):return java_list([json.dumps(s,ensure_ascii=False) for s in values])
def java_option(o):return 'new TaxonomyRegistry.Option('+','.join([json.dumps(o['code']),json.dumps(o['label'],ensure_ascii=False),java_strings(o['types']),java_strings(o['subjects']),java_strings(o['works'])])+')'
java_fields=[]
for f in fields:
    types=java_list(['new TaxonomyRegistry.EventType('+json.dumps(t['code'])+','+json.dumps(t['label'],ensure_ascii=False)+')' for t in f['types']])
    java_fields.append('new TaxonomyRegistry.Field('+','.join([json.dumps(f['key']),json.dumps(f['code']),json.dumps(f['label'],ensure_ascii=False),types,java_list([java_option(o) for o in f['formats']]),java_list([java_option(o) for o in f['topics']])])+')')
outputs={
 'backend/src/main/java/com/boothhana/interests/TaxonomyRegistryData.java':'// Generated by scripts/sync-taxonomy.py. Edit taxonomy/catalog.json.\npackage com.boothhana.interests;\nimport java.util.List;\nfinal class TaxonomyRegistryData {\n private TaxonomyRegistryData() {}\n static List<TaxonomyRegistry.Field> fields() { return List.of(\n  '+',\n  '.join(java_fields)+'\n ); }\n}\n',
 'collector/catalog-taxonomy.json':raw,
 'frontend/seo/taxonomy.mjs':'// Generated by scripts/sync-taxonomy.py. Edit taxonomy/catalog.json.\nexport const taxonomy = '+json.dumps(data,ensure_ascii=False,indent=2)+'\n',
 'frontend/seo/taxonomy.d.mts':"// Generated by scripts/sync-taxonomy.py.\nexport type EventType = "+' | '.join(repr(t) for t in all_types)+"\nexport interface TaxonomyOption { code: string; label: string; types: string[]; subjects: string[]; works: string[] }\nexport interface TaxonomyField { key: "+' | '.join(repr(f['key']) for f in fields)+"; code: "+' | '.join(repr(f['code']) for f in fields)+"; label: string; types: { code: EventType; label: string; aliasOf?: EventType }[]; formats: TaxonomyOption[]; topics: TaxonomyOption[] }\nexport const taxonomy: { version: number; fields: TaxonomyField[] }\n"
}
for filename in ('search-result.schema.json','event-result-v4.schema.json'):
    path=ROOT/'collector/schemas'/filename
    schema=json.loads(path.read_text(encoding='utf-8'))
    schema['properties']['events']['items']['properties']['subcategory']['enum']=all_types
    outputs[str(path.relative_to(ROOT))]=json.dumps(schema,ensure_ascii=False,indent=2)+'\n'

paragraphs=['<!-- TAXONOMY:START -->','행사명 키워드만으로 유형을 추정하지 않는다. 공식 소개·행사 목적·프로그램을 확인한다.']
for field in fields:
    paragraphs += [field['label']+' 유형: '+', '.join(t['code']+'('+t['label']+')' for t in field['types'] if not t.get('aliasOf'))+'.',
                   field['label']+' 취향 주제: '+', '.join(t['code']+'('+t['label']+')' for t in field['topics'])+'.']
paragraphs += ['subjects에는 확인된 취향 주제의 표준 코드와 작품·캐릭터 원문 태그를 함께 기록한다. ONLY_EVENT, BIRTHDAY_CAFE 등 행사 유형만을 주제 대신 넣지 않는다. 표준 주제와 작품은 별개이며 원문 근거를 sources에 남긴다.',
 '공식 한정 운영 팝업은 판매·체험·전시·복합 목적에 맞는 POPUP_RETAIL/POPUP_EXPERIENCE/POPUP_EXHIBITION/POPUP_MIXED를 사용한다. 공식 소개로 확인한 취향 주제만 기록한다. 상설 체험관은 팝업으로 추정하지 않는다. 티켓 사용기한이나 프리오픈 종료일을 행사 종료일로 쓰지 않는다. 종료일이 확인되지 않으면 후보로 남겨 재확인한다.',
 '팝업과 서브컬처는 별도 분야다. 캐릭터·애니·게임·버튜버 주제의 팝업도 POPUP_*로 분류하고 주제는 subjects에 기록한다. 판매점·브랜드의 한정 운영 팝업을 STATIONERY_GOODS/CHARACTER_ART 등 서브컬처 유형으로 바꾸지 않는다. 동인·온리전·생일카페·팬 행사·관련 공연은 공식 행사 목적에 맞는 서브컬처 유형으로 유지한다. POPUP_STORE는 기존 데이터 호환 코드이므로 신규 수집에는 사용하지 않는다.',
 '생일 기념이 확인된 경우에만 BIRTHDAY_CAFE를 사용하고 일반 팬카페는 FAN_CAFE로 둔다. 일반 음악 공연은 FESTIVAL의 CONCERT/MUSIC_FESTIVAL로 구분하고, 애니·게임 OST·버추얼 중심 공연만 SUBCULTURE_MUSIC로 둔다. 일반 브랜드 팝업을 팬덤 행사로 추정하지 않는다.',
 '<!-- TAXONOMY:END -->']
block='\n'.join(paragraphs)
for filename in ('subculture.md','events-v4.md','event-enrichment.md','event-candidate.md'):
    path=ROOT/'collector/prompts'/filename
    value=path.read_text(encoding='utf-8')
    if '<!-- TAXONOMY:START -->' in value:
        before,rest=value.split('<!-- TAXONOMY:START -->',1)
        _,after=rest.split('<!-- TAXONOMY:END -->',1)
        value=before+block+after
    else:value=value.rstrip()+'\n\n'+block+'\n'
    outputs[str(path.relative_to(ROOT))]=value

stale=[]
for name,value in outputs.items():
    path=ROOT/name
    if path.exists() and path.read_text(encoding='utf-8')==value:continue
    if '--check' in sys.argv:stale.append(name)
    else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(value,encoding='utf-8')
if stale:raise SystemExit('Taxonomy copies are stale; run python scripts/sync-taxonomy.py:\n'+'\n'.join(stale))
print('Taxonomy synchronized:',len(fields),'fields,',len(all_types),'event types')
