const {test}=require('node:test'),assert=require('node:assert/strict');
const {runtime,wait}=require('./support/runtime.cjs');
function setup(){const h=runtime(),{useRemote}=h.load('frontend/src/app/useRemote.ts');let key='A',loader=()=>Promise.resolve('initial');
 const render=()=>h.render(()=>useRemote('verification:v22:remote',loader,[key]));render();h.flushEffects();return {h,render,setLoader:x=>loader=x,setKey:x=>key=x};}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('a successful explicit write replaces an older in-flight GET result',async()=>{const x=setup();await settle();const delayed=wait();x.setLoader(()=>delayed.promise); // reload captures the current scope loader: change key deliberately
 x.setKey('B');x.render();x.h.flushEffects();x.render().setData('saved revision 2');delayed.resolve('stale revision 1');await settle();assert.equal(x.render().data,'saved revision 2');assert.equal(x.render().loading,false);});
test('older GET failure cannot erase successful write or display a false error',async()=>{const x=setup();await settle();const delayed=wait();x.setLoader(()=>delayed.promise);x.setKey('B');x.render();x.h.flushEffects();x.render().setData('saved');delayed.reject(Error('old lookup failed'));await settle();assert.equal(x.render().data,'saved');assert.equal(x.render().error,null)});
test('functional setter also invalidates the earlier GET',async()=>{const x=setup();await settle();const delayed=wait();x.setLoader(()=>delayed.promise);x.setKey('B');x.render();x.h.flushEffects();x.render().setData(()=>({revision:3}));delayed.resolve({revision:1});await settle();assert.equal(x.render().data.revision,3)});
test('reload started after setData can still replace the saved state',async()=>{const x=setup();await settle();let count=0;const delayed=wait();x.setLoader(()=>++count===1?delayed.promise:Promise.resolve('new server revision'));x.setKey('B');x.render();x.h.flushEffects();x.render().setData('saved');await x.render().reload();delayed.resolve('old');await settle();assert.equal(x.render().data,'new server revision')});
test('setter from inactive scope never overwrites a different lookup',async()=>{const x=setup();await settle();const old=x.render();x.setKey('B');x.setLoader(async()=>'B');x.render();x.h.flushEffects();await settle();old.setData('A');assert.equal(x.render().data,'B')});
test('ordinary successful reloads without explicit writes still work',async()=>{const x=setup();await settle();assert.equal(x.render().data,'initial');await x.render().reload();assert.equal(x.render().data,'initial');assert.equal(x.render().error,null)});
